### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'

### ISSUE THREAD

**Issue by jgmuchiri** [TheLastGimbus/GooglePhotosTakeoutHelper#100]
Am I missing something here?

![image](https://user-images.githubusercontent.com/4142133/136301409-5e2e52e8-93fb-411e-867d-dee6f077bbe5.png)

**Comment by TheLastGimbus** [comment]
Looks like you're executing this as `root` user? You shouldn't be doing this...

**Comment by jgmuchiri** [comment]
@TheLastGimbus I was giving `root` as shot since other users didn't work either. By the way this is inside a docker container to test this out, so not too keen on running it in elevated privileges.

**Comment by jgmuchiri** [comment]
![image](https://user-images.githubusercontent.com/4142133/139956616-a139c084-9931-4308-a9ef-759242c2be37.png)

**Comment by TheLastGimbus** [comment]
> this is inside a docker

Oh, this may be something: the line that crashes changes something with `stdout` to have nicer logs - it may work different or something ;_; - you can try to clone the source code and just comment it out...

**Comment by TheLastGimbus** [comment]
Let me know if I can help a bit - perhaps if you post your docker config we can try to figure it out 👍

**Comment by tremosian** [comment]
I ran into this error today, and figured out a solution:

reconfigure is only becomes an option in python 3.7, not the OP's 3.6.9 (solution that worked for me: update to python 3.7).
