### ISSUE TITLE
Tool fails if images and metadata are split across multiple Google Photos downloads

### ISSUE THREAD

**Issue by jacobastern** [TheLastGimbus/GooglePhotosTakeoutHelper#104]
I ran your tool, and it worked great - except when images and metadata were split, due to Google Photos download size limits. In my case, I had two downloads, photos1 (~50GB) and photos2 (~25 GB). I used your tool to process these folders independently from each other, and ended up with a lot of files where the tool failed to merge the metadata. Turns out that Google Photos doesn't split your download neatly by date or even by photo. I had many photos for which img_name.jpg.json was in one download, and img_name.jpg was in another. Merging the download folders fixed the problem.

I'm not sure the best way to address this problem -- it's not really a problem with this tool, more a problem with Google Photos, but I anticipate that many users who use the tool on the download folders separately will run into the same problem.

Perhaps the best way is just to document it - put a warning in the README telling users to merge google photos download folders before running the tool. Another alternative would be to allow for multiple input folders, and it searches but that would add to the complexity of the tool.

What are your thoughts on the best solution here?

**Comment by TheLastGimbus** [comment]
> Perhaps the best way is just to document it

Yep, looks like it is

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/1a4912d23b68bd8dac0e2a17a5931d8e3661f2da/README.md?plain=1#L18

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/1a4912d23b68bd8dac0e2a17a5931d8e3661f2da/README.md?plain=1#L32

Here it is right there :grin:
