### ISSUE TITLE
Can't use spaces in path

### ISSUE THREAD

**Issue by OnlyMalinka** [TheLastGimbus/GooglePhotosTakeoutHelper#107]
If you use spaces in path to your folders, the script says:
`google-photos-takeout-helper -i D:\Takeout\Google Photo -o D:\New Folder
usage: google-photos-takeout-helper -i [INPUT TAKEOUT FOLDER] -o [OUTPUT FOLDER]
Google Photos Takeout Helper: error: unrecognized arguments: Фото папка`

**Comment by TheLastGimbus** [comment]
this is how cmd works. You need to put "c:\path with spaces" - `"`
