### ISSUE TITLE
Inconsistency of "duplicate removal" + missing transperancy

### ISSUE THREAD

**Issue by Speedylux** [TheLastGimbus/GooglePhotosTakeoutHelper#110]
Hi all,

I just tried the script with an example file-set of mine but currently struggling with the logic and the transparency when it comes to the removal of duplicates.

```
4116 Input files (according the beginning of the script)

3482 calculating small hashes
 580 full hashes
 574 removing duplicates

Final statistics:
Removed duplicates: 630
```

1. How are the numbers related to each other as I cannot see them matching each other right away
- _number of input files_
- _number of caluclated small hashes_
- _full hashes_
- _removing duplicates_ 
- _removed duplicates (final statistics)_ --> number is larger than _removing duplicates_ (?)

2. How to allocate the deleted files to validate this manually?
I am clearly no expert in this but it seems odd to me that >15% in my example should be duplicates. Without reviewing this by myself it feels that I will loose data. How to avoid that no false-positive in the duplicate assignment is happening?

Would appreciate any support.
Thanks

**Comment by TheLastGimbus** [comment]
Hi there!

Sorry for not asnwearing long :(

Uhhh... i don't remember honestly... there may be ways that script deletes duplicates that it finds later... - some "-EDITED.jpg" stuff etc...

To make everything nice and transparent, I think a rewrite of the whole script would be needed...

**Comment by MrModest** [comment]
I assume that Google can put the same photo in a custom-created album and a generated year's album. So when you unify files from all folders, you get duplicates.

**Comment by TheLastGimbus** [comment]
`v3` should be very reliable and consistent - if it's not, let me know and i'll reopen this :+1:
