### ISSUE TITLE
Oh, boy. Non-developer here. With Google Takeout Problems.

### ISSUE THREAD

**Issue by belleduchene** [TheLastGimbus/GooglePhotosTakeoutHelper#118]
I have searched EVERYWHERE for a resource to help merge/migrate Google Takeouts for non-dev people. 

Some amazing people like yourself have created ways to do Google PHOTOS, specifically, which is great. But I exported ALL of my Drive with millions of files. And now each file has been blown up into random folders. For 9 hours I tried to copy/paste manually but it's ROUGH.

What to do? I'm a Mac. The Terminal thing-y didn't go so hot for me.

**Comment by TheLastGimbus** [comment]
Yo man :call_me_hand: 

So you mean you exported stuff from Google Drive... and it's scattered all over the place? I'm afraid my script can't help with that :confounded: 

If you really wanted, I could maybe look around and write some script just for you/for that puprouse if it was common... but that won't be very fast...

Good luck!

**Comment by belleduchene** [comment]
I think it's a thing! A lot of people grumble about it. Google customer service couldn't help--and I'm like hey, I'm not the only one who is having a problem.

It's like this (imagine with me).... I downloaded a bag of grapes (files) and an orange (photos) from Google Drive. Instead of downloading as complete pieces of fruit, they downloaded into a ton of .zips that put a few grapes (files) into each one and the only way to put them back together is to do it one by one. On top of that, they sliced the orange (photos) into pieces and divided each piece into a photo file and a .jsor metadata file, that won't work unless combined--but they are in different files and even when you put them side by side, they don't combine.

This really is hell.

**Comment by Maltavius** [comment]
You just select all of the Zip files, right click and select Extract (on Windows).
They will all end up in a big folder.
On that folder you run this program. It sorts out as much as it can.

**Comment by belleduchene** [comment]
Thanks, Maltavius. I'm Mac, so I'll have to figure something out. What program are you referencing?

**Comment by Maltavius** [comment]
> Thanks, Maltavius. I'm Mac, so I'll have to figure something out. What program are you referencing?

https://support.apple.com/en-gb/guide/mac-help/mchlp2528/mac

This program the one in. This. GitHubPage

**Comment by belleduchene** [comment]
Hmmm that link didn't work.

**Comment by Maltavius** [comment]
> Hmmm that link didn't work.

Yes it does.

This program here only handles photos. Look at other projects to handle the other files you've exported.

Since I suspect you are trolling I'll not answer anymore.

**Comment by belleduchene** [comment]
It showed a message that said "We're Sorry" before. Now it is working..... Just another reason why I want to move to a deserted island with NO COMPUTERS. Maybe someday?!?

Not trolling. Don't even know what that means. Thanks for the help.

**Comment by TheLastGimbus** [comment]
I'm not sure if you resolved the issue or not, but good luck anyway! I'll close this for now :+1:
