### ISSUE TITLE
Skip folder matching name

### ISSUE THREAD

**Issue by bartkodden** [TheLastGimbus/GooglePhotosTakeoutHelper#127]
Great tool, everything works as expected.
However when running this on my "older" takeout export it also wants to copy the automatically generated synology photos thumbnail files (3 for each image) .
This makes the script very slow and adds 3x more files to move.
The thumbnails are placed in a system folder "@eaDir"

Is there a way to simply skip these folders? thanks for your help!

**Comment by TheLastGimbus** [comment]
You could download the scirpt, modify extra-formats to match your files: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/155b0cfe3dc9f7b4d06081d7d4d6c9ec635096ef/google_photos_takeout_helper/__main__.py#L118-L124 and use `--skip-extras`

**Comment by TheLastGimbus** [comment]
Hi there!

`v3` should be way faster and more consistent - will copy just the images from year folders, and albums should not slow it down by much :+1:
