### ISSUE TITLE
Doesn't work - maybe a bug

### ISSUE THREAD

**Issue by climpyx** [TheLastGimbus/GooglePhotosTakeoutHelper#132]
No matter how many times I tried the app it doesn't work. I tried running as administrator, turned off firewalls but still won't turn on.

**Comment by climpyx** [comment]
I tried with an old version of script. ([v2.3.0](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/releases/tag/v2.3.0) And it worked.

**Comment by TheLastGimbus** [comment]
Oooookayy, interesting - can you paste me the console/screenshot of it?

**Comment by climpyx** [comment]
Actually, when I start the script, nothing happens directly.

**Comment by TheLastGimbus** [comment]
> can you paste me the console/screenshot of it?

**Comment by TheLastGimbus** [comment]
Will reopen if any valid info
