### ISSUE TITLE
Nice message instead of exception when no photos

### ISSUE THREAD

**Issue by preppietechie** [TheLastGimbus/GooglePhotosTakeoutHelper#134]
I've got the contents of my google photos takeout zip files extracted to c:\user\username\desktop\photos-decompress\Takeout\GooglePhotos\ (so it's a big folder full of dated subfolders which, in turn contain the images and json files). 

Running v3.0, It appears that it can't find any contents of the specified folder, and I get the following error: 

C:\Users\Username\Downloads> gpth-v3.0.0-Windows.exe -i C:\users\Username\Desktop\photos-decompress\Takeout\GooglePhotos\ -o C:\users\Username\Desktop\photos-decompress\cu\
WARNING: Script will *move* files from input to output - not *copy*
- this is faster, and doesn't use extra space, but will break your
input folder (it will be, well, empty)
If you want copy instead of move, exit script (ctrl-c) and use --copy flag
Otherwise, press enter to agree with that

Okay, running... searching for everything in input folder...
Found 0 photos/videos in input folder
Unhandled exception:
Unsupported operation: Infinity or NaN toInt
#0      FillingBar._render (package:console_bars/src/filling_bar.dart)
#1      new FillingBar (package:console_bars/src/filling_bar.dart:73)
#2      main (file:///d:/a/googlephotostakeouthelper/googlephotostakeouthelper/bin/gpth.dart:220)
<asynchronous suspension>
C:\Users\username\Downloads>

**Comment by preppietechie** [comment]
It also does the same thing if I specify c:\users\username\Desktop\photos-decompress\Takeout\

**Comment by TheLastGimbus** [comment]
huh, weird... do you have "year folders" in your takeout? folders named like "Photos from 2016" ? or just albums

**Comment by preppietechie** [comment]
just the albums... folders like:

C:\Users\username\Desktop\photos-decompress\Takeout\Google Photos\1-27-12\
and
C:\Users\username\Desktop\photos-decompress\Takeout\Google Photos\2013 San Francisco\

with photos and json files inside them.

**Comment by TheLastGimbus** [comment]
Okay then - new script takes *all* photos **only** from year folders, and looks up at albums only to link the information about them (which it currently does nothing with, see #135)

If you can, just take the new export from google and select only "photos from ..." folders

Otherwise, best option is to use old python version

Is there some particular reason you have this like that? I may change the behavior of current code if there is...

**Comment by preppietechie** [comment]
I think it’s a throwback to the old Picasso days maybe? Honestly it’s been
this way so long I’m unsure of exactly when it started. I wouldn’t make any
changes that limit 3.x for my edge case. I’ll chug along with 2.3.1. You’ve
written an amazing tool! Thank you!

**Comment by TheLastGimbus** [comment]
Okay so... when you took your takeout, you selected all the folders, and that's just the way yours is?

**Comment by KM192** [comment]
I have the same issue. My case is that I would like to take from Google only photos from albums, while they are well organized by me. I do not care or even do not want to take all pictures from whole years. is there a chance that program would take pictures from all albums and would re-create album structure in the output folder ?

**Comment by TheLastGimbus** [comment]
@KM192 Yeah, i think this will be main "album impementation". See #135  discussion for that 

Looks like I will have to change behaviour of photo-finding... created #140 for that

**Comment by llliax** [comment]
For a long time I could not understand why all my photos did not want to be converted. Please add in bold to the instructions that the photos should be at the root of the year folder. Then the transfer happens. The transfer is lightning fast! Thank you for your work!

**Comment by TheLastGimbus** [comment]
For now, gpth just prints a nice message. I won't implement "Albums only" mode because it would complicate stuff very much. 

@llliax there is now interactive mode which exports the zips *for you*, leaving no place for user error (other than wrongly selecting zips) - hope this fixes your problem :grin: !
