### ISSUE TITLE
FileSystemException when timestamp is negative

### ISSUE THREAD

**Issue by wjhladik** [TheLastGimbus/GooglePhotosTakeoutHelper#136]
![image](https://user-images.githubusercontent.com/49169905/208714530-5170d343-9d3f-4e8c-9a58-4112ae030fe4.png)

![image](https://user-images.githubusercontent.com/49169905/208714637-44ae8374-9e92-4152-bc6f-95118b77789d.png)

I set the date and time in GP for this very old 1904 photo. But the stamp in the json file is negative - maybe that's the issue.

**Comment by TheLastGimbus** [comment]
Ahhh, yes I did have this issue in the past with Python version. I'll see and let you know :+1:

by the way, i see you have a lot of "can't get date on" with `-edited` and `...(1)` photos - I will also try to fix that in near future

**Comment by wjhladik** [comment]
Thank you.

**Comment by iamjcsji** [comment]
I'm having the same issue and looking forward to the next release. It sends an exception when there are like 200 photos left to move in a total of 18k. I'm waiting for the next release to export the photos 😁. Thanks a lot for your work on this project!
