### ISSUE TITLE
Change instructions and code to process Archive album

### ISSUE THREAD

**Issue by wjhladik** [TheLastGimbus/GooglePhotosTakeoutHelper#138]
The Archive album should be included in Takeout in addition to all the Photos from XXXX albums. Those photos are not in any of the Photos from XXXX albums. I personally keep important photos in Archive, but ones I just don't want cluttering the main space. Not sure if your code will process this album if it's present.

**Comment by TheLastGimbus** [comment]
Done! Watch for a new release
