### ISSUE TITLE
unhandled exception (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by mcraven077** [TheLastGimbus/GooglePhotosTakeoutHelper#139]
I'm receiving an error stating the following.  I've included screenshots from the start and the error.

Unhandled exception:
FileSystemException: Cannot rename file to 'C:\Users\mcrav\Downloads\Photos\PICT1214.JPG', path = 'C:\Users\mcrav\Downloads\Google Photos Takeout\Takeout\Google Photos\Photos from 2001\PICT1214.JPG' (OS Error: Access is denied.
, errno = 5)
#0      _File.rename.<anonymous closure> (dart:io/file_impl.dart:305)
<asynchronous suspension>
#1      main (file:///d:/a/googlephotostakeouthelper/googlephotostakeouthelper/bin/gpth.dart:294)
<asynchronous suspension>

![Screenshot 2022-12-28 230728](https://user-images.githubusercontent.com/121594215/209902227-76f9d3f1-27bb-4686-ad73-c7eb88c31932.png)
![Screenshot 2022-12-28 230746](https://user-images.githubusercontent.com/121594215/209902228-f132e7a9-f229-425b-9a68-214f3953bc89.png)

**Comment by mcraven077** [comment]
The issue was the Norton Data Protector.  I had disabled Antivirus and Firewall, but Data Protector was still enabled.

**Comment by TheLastGimbus** [comment]
Happy it works!
