### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by Xielipton** [TheLastGimbus/GooglePhotosTakeoutHelper#145]
The memory cannot be released and cannot be exported correctly. Now my Google Photos compressed file is close to 200G. When running the script, the 32G memory occupies 95% and cannot be released, and the script cannot continue. Later, in the test of ubuntu with 4G memory and Macbook pro with 16G memory, the script was terminated because the memory could not be released.

**Comment by TheLastGimbus** [comment]
Ah, shit, i was afraid of this. The `archive` Dart library was known to use memory, but i though i fixed this - will try again soon 👍

**Comment by TheLastGimbus** [comment]
turned out it was just a small `asyncWrite: true` flag :D - should be good now, go test it out!
