### ISSUE TITLE
It doesn't seem to like tgz files

### ISSUE THREAD

**Issue by johnnysbug** [TheLastGimbus/GooglePhotosTakeoutHelper#147]
Hi, I was trying to use this tool and my files are saved as `tgz`.

I noticed it seems to be an allowed format [here](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/master/lib/interactive.dart#L82) in `interactive.dart`, but there is a check a few lines later that only looks for `.zip` extensions [here](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/master/lib/interactive.dart#L103).

I am going to see if I can get around this locally by changing the code, but I wasn't sure if this was intended behavior.

**Comment by TheLastGimbus** [comment]
Another example of me fixing bugs then reintroducing them again :laughing: - should work in next version :) - thanks for reporting!!
