### ISSUE TITLE
v3.3.0 Cannot get date on (almost) every .MP4 file 

### ISSUE THREAD

**Issue by GiovanniBaccichet** [TheLastGimbus/GooglePhotosTakeoutHelper#148]
Hi,
I just processed 500+ GB of Google Photos takeout and noticed that almost every .MP4 file got transferred into the date-unknown folder, even though in the .JSON files attached there is the correct metadata (and it wasn't transferred). Am I doing something wrong?

This is the command I used:
`./gpth-macos -i <takeout-folder> -o <output-folder> --divide-to-dates`

Best regards,
GB

**Comment by TheLastGimbus** [comment]
will reopen if any more comments will show up
