### ISSUE TITLE
Synology DSM7 Linux:  Exception: Couldn't find the executable zenity in the path

### ISSUE THREAD

**Issue by IamMattM** [TheLastGimbus/GooglePhotosTakeoutHelper#150]
Trying for first time the chmod-ed +x utility under <Linux DiskStation 4.4.180+> (Synology DSM7 fork) but it seems to be looking for a utility called "zenity"

 `GooglePhotosTakeoutHelper v3.3.0
Hi there! This tool will help you to get all of your photos from Google Takeout to one nice tidy folder

(If any part confuses you, read the guide on:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper )

First, select all .zips from Google Takeout (use Ctrl to select multiple)
[press enter to continue]

Unhandled exception:
Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker_desktop/src/file_picker_utils.dart:96)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker_desktop/src/file_picker_linux.dart:95)
<asynchronous suspension>
#2      FilePickerLinux.pickFiles (package:file_picker_desktop/src/file_picker_linux.dart:19)
<asynchronous suspension>
#3      getZips (package:gpth/interactive.dart:79)
<asynchronous suspension>
#4      main (file:///home/runner/work/GooglePhotosTakeoutHelper/GooglePhotosTakeoutHelper/bin/gpth.dart:86)
<asynchronous suspension>
`

**Comment by TheLastGimbus** [comment]
Yess, exactly - if you are tech-savy, using it only in cli, using cli options will be even faster for you since you can use dedicated tool like `p7zip` to extract the files (which should be a *bit* faster that Dart)
