### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by choodique** [TheLastGimbus/GooglePhotosTakeoutHelper#152]
Whether there are plans to support M1 processors?

**Comment by choodique** [comment]
Please close the issue.
Solved the problem by installing Rosetta 2 in `Terminal`:
`softwareupdate --install-rosetta`

**Comment by TheLastGimbus** [comment]
Yep, just enable emulation as you did

To compile to M1 i would need an M1... and i do not have that :shrug:
