### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by AlbertLukm** [TheLastGimbus/GooglePhotosTakeoutHelper#160]
Hello, make it possible to select a time zone. Now it sets the default time zone.

**Comment by TheLastGimbus** [comment]
sorry but i have a lof of issues going on - and definetley messing with one of the worst programmings topics that time zones are - is not interesting for me now

for now, you can try doing this with exiftool: https://exiftool.org/forum/index.php?topic=10583.msg56073#msg56073

**Comment by TheLastGimbus** [comment]
you need to figure this out yourself, sorry - try experimenting with single sample file :+1:

**Comment by AlbertLukm** [comment]
okay

**Comment by AlbertLukm** [comment]
Hello, unfortunately I did not succeed

**Comment by TheLastGimbus** [comment]
that's sad :( but don't give up! keep trying and experimenting, you'll learn something new!
