### ISSUE TITLE
Unhandled exception: `FileSystemException: readInto`

### ISSUE THREAD

**Issue by matt-boris** [TheLastGimbus/GooglePhotosTakeoutHelper#162]
Hey there, I'm getting this error while trying to run your tool against my large (50GB) `tgz` takeout files. Please let me know if you need anything more from me regarding this error.

```bash
Unzipping takeout-20230122T143523Z-001.tgz...
Unhandled exception:
FileSystemException: readInto failed, path = '/var/folders/_c/z_r8csbn73j2dt50rsxg68hr0000gn/T/dart_archive9Hnqal/temp.tar' (OS Error: Invalid argument, errno = 22)
#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:799)
#1      FileHandle.readInto (package:archive/src/io/input_file_stream.dart:60)
#2      InputFileStream.toUint8List (package:archive/src/io/input_file_stream.dart:326)
#3      ArchiveFile.decompress (package:archive/src/archive_file.dart:169)
#4      ArchiveFile.content (package:archive/src/archive_file.dart:134)
#5      extractFileToDisk (package:archive/src/io/extract_archive_to_disk.dart:127)
<asynchronous suspension>
#6      unzip (package:gpth/interactive.dart:219)
<asynchronous suspension>
#7      main (file:///Users/runner/work/GooglePhotosTakeoutHelper/GooglePhotosTakeoutHelper/bin/gpth.dart:103)
<asynchronous suspension>
```

And is there anything that can be done about the speed of unpack these files? These 50GB `tgz`'s are taking _forever_!

Thanks!

**Comment by TheLastGimbus** [comment]
Hi! Huh, best solution for you, to both fix the error and speed up the unpacking, is to just unpack yourself (with some external tool) and use gpth with cli arguments. Look them up with `gpth --help`, and you should figure it out, but text here if you need some help :+1:

**Comment by TheLastGimbus** [comment]
Oh, another NAS-samba-to-mac guy 0_o why are you guys doing it :fearful:  ?

Anyway, happy it works! I'll look at the pr in mean time :+1:
