### ISSUE TITLE
Month folder on 2 digits when using --divide-to-dates option

### ISSUE THREAD

**Issue by denouche** [TheLastGimbus/GooglePhotosTakeoutHelper#167]
Hello,

I'm migrating on the v3 version (thank a lot for this great version!! :clap: )

On the v2 when using --divide-to-dates option generated month forlders on 2 digits, for example 2022/02/
thank to this line:
```python
    new_path = f"{FIXED_DIR}/{date.year}/{date.month:02}/"
```

On the new v3 version the month folders are on 1 digit for the 9 first months of the year, for example 2022/2/
It's not a big problem but the folders are not well sorted when listing. :sweat_smile: 

Is it possible to add a leading zero when the month representation is on 1 digit?
Thanks!

**Comment by denouche** [comment]
I'm not familiar with Dart, but maybe something like this would do the job?
```
: p.join(output.path, '${date.year}', date.month.toString().padLeft(2, '0'))
```
here:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/919e2cf0e09b59943adb9e82acfc3b57508be6a9/bin/gpth.dart#L338
?

**Comment by denouche** [comment]
Ok after playing on https://dartpad.dev/ it seems this works as expected. I will do the PR.

**Comment by brock** [comment]
Just getting caught up on the release, but would it be possible to make this configurable? I personally use YYYY/YYYY-MM for my folders.

**Comment by TheLastGimbus** [comment]
oh by the way i forgot to include this in release D: - next one with potential memory fixes will :pray:

> make this configurable

Probably not, that would be too much options. but i remember this Polish rename tool called szyszka: https://github.com/qarmin/szyszka/releases
