### ISSUE TITLE
Error code 13

### ISSUE THREAD

**Issue by Nuwesh** [TheLastGimbus/GooglePhotosTakeoutHelper#170]
After interacting with it it shows the error

Unzipping takeout-20230206T082054Z-001.zip...

Okay, running... searching for everything in input folder...
Found 0 photos/videos in input folder
...oh :(
...
I couldn't find any D: reasons for this may be:
  - you've already ran gpth and it moved all photos to output -
    delete the input folder and re-extract the zip
  - your Takeout doesn't have any "year folders" -
    visit https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper
    again and request new, correct Takeout
After fixing this, go ahead and try again :)
([interactive] removing unzipped folder...)
[gpth quitted :( (code 13) - press enter to close]

**Comment by TheLastGimbus** [comment]
Did you read what it says and checked if it's true or not?

**Comment by Nuwesh** [comment]
> 

I apologise for wasting your valuable time. I identified the problem (there was a problem in my takeout). People who made and are managing this Utility and actively helping in issues are God 🙏🛐
