### ISSUE TITLE
[gpth quitted :( (code 69) - press enter to close]

### ISSUE THREAD

**Issue by trueno40** [TheLastGimbus/GooglePhotosTakeoutHelper#173]
Unzipping takeout-20230210XXXXX.zip...
Error while unzipping File: 'C:\Users\XXXXX\Downloads\takeout-20230210XXXXX.zip' :(
FormatException: Unexpected extension byte (at offset 108)
[gpth quitted :( (code 69) - press enter to close]

**Comment by TheLastGimbus** [comment]
Oh 💩

Umm, try to re-take your takeout, and maybe use the tar format if zip still doesn't work

**Comment by trueno40** [comment]
> Oh 💩
> 
> Umm, try to re-take your takeout, and maybe use the tar format if zip still doesn't work

So I downloaded it again as a zip and it worked this time.  Only difference was the first time I pulled the takeout zips I extracted them myself, then when I discovered your app, I re-zipped them myself.  I think me not using the exact same naming convention was the downfall.

**Comment by TheLastGimbus** [comment]
Happy it works!
