### ISSUE TITLE
Interactive unzipping fails on Windoza

### ISSUE THREAD

**Issue by tribulete** [TheLastGimbus/GooglePhotosTakeoutHelper#178]
Hello. Thanks for the fix to issue  #172, but I have a new issue relationed with this:

With version 3.3.4:

```
GooglePhotosTakeoutHelper v3.3.4
Hi there! This tool will help you to get all of your photos from Google Takeout to one nice tidy folder

(If any part confuses you, read the guide on:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper )

First, select all .zips from Google Takeout (use Ctrl to select multiple)
[press enter to continue]

Cool!

Now, select output folder - all photos will be extracted there
[press enter to continue]

Cool!

Do you want your photos in one big chronological folder, or divided to folders by year/month?
[1] (default) - one big folder
[2] - year/month folders
(Type 1 or 2 or press enter for default):
1
Okay, one big it is!

(Note: everything will take ~292.69 GiB of disk space - you have 689.11 GiB free so should be fine :)
[press enter to continue]


gpth will now unzip all of that, process it and put everything in the output folder :)
[press enter to continue]

Unzipping takeout-20230131T115153Z-001.zip...
Error while unzipping File: 'D:\takeout\takeout-20230131T115153Z-001.zip' :(
PathNotFoundException: Cannot create file, path = 'D:\takeout\.gpth-unzipped\Takeout\Google Photos\Viaje Colombia \metadata.json' (OS Error: El sistema no puede encontrar la ruta especificada.
, errno = 3)
[gpth quitted :( (code 69) - press enter to close]
```

Now, the path "D:\takeout\.gpth-unzipped\Takeout\Google Photos\Viaje Colombia \metadata.json" has the backslash correctly, but there is a blank space between "Colombia" and "\Metadata.json". 

The original directory "Viaje colombia" doesn`t have that space.

**Comment by omlet05** [comment]
I have something related with the latest release:

Unzipping takeout-20230220T165030Z-001.zip...
Error while unzipping File: 'H:\Downloads\takeout-20230220T165030Z-001.zip' :(
PathNotFoundException: Cannot create file, path = 'H:\Downloads\gphoto\.gpth-unzipped\Takeout\Google Photos\@bxl \métadonnées.json' (OS Error: Le chemin d’accès spécifié est introuvable.

**Comment by TheLastGimbus** [comment]
Ehh, here we go again

I'll try to look into that in some time

Meanwhile, you guys can just unzip manually and use cmd options:

`gpth -i "C:\your\input\folder" -o "C:\output\folder"`

Read them up with more detail by running `gpth --help` in the cmd

**Comment by LPFchan** [comment]
```
GooglePhotosTakeoutHelper v3.3.4
gpth will now unzip all of that, process it and put everything in the output folder :)
[press enter to continue]

Unzipping takeout-20230226T014841Z-001.zip...
Error while unzipping File: 'D:\Cloud Backups\google photos takeout\Takeout 2023-02-26\takeout-20230226T014841Z-001.zip' :(
PathNotFoundException: Cannot create file, path = 'D:\Cloud Backups\google photos takeout\Takeout 2023-02-26\output\.gpth-unzipped\Takeout\Google Photos\ \metadata.json' (OS Error: 지정된 경로를 찾을 수 없습니다.
, errno = 3)
[gpth quitted :( (code 69) - press enter to close]
```

Same problem here!

**Comment by TheLastGimbus** [comment]
Seems you all have not-english language... that may be something

@shlomis1 is your issue resolved?

**Comment by shlomis1** [comment]
@TheLastGimbus Nope. Same problem still :(
```
GooglePhotosTakeoutHelper v3.3.4
Hi there! This tool will help you to get all of your photos from Google Takeout to one nice tidy folder

(If any part confuses you, read the guide on:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper )

First, select all .zips from Google Takeout (use Ctrl to select multiple)
[press enter to continue]

Cool!

Now, select output folder - all photos will be extracted there
[press enter to continue]

Cool!

Do you want your photos in one big chronological folder, or divided to folders by year/month?
[1] (default) - one big folder
[2] - year/month folders
(Type 1 or 2 or press enter for default):
2
Okay, will divide to folders!

(Note: everything will take ~218.47 GiB of disk space - you have 2.02 TiB free so should be fine :)
[press enter to continue]


gpth will now unzip all of that, process it and put everything in the output folder :)
[press enter to continue]

Unzipping takeout-20230207T165218Z-001.zip...
Error while unzipping File: 'F:\Downloads\takeout-20230207T165218Z-001.zip' :(
PathNotFoundException: Cannot create file, path = 'F:\Test\.gpth-unzipped\Takeout\Google Photos\Design \metadata.json' (OS Error: The system cannot find the path specified.
, errno = 3)
[gpth quitted :( (code 69) - press enter to close]
```

**Comment by tribulete** [comment]
> Ehh, here we go again
> 
> I'll try to look into that in some time
> 
> Meanwhile, you guys can just unzip manually and use cmd options:
> 
> `gpth -i "C:\your\input\folder" -o "C:\output\folder"`
> 
> Read them up with more detail by running `gpth --help` in the cmd

Thanks

**Comment by TheLastGimbus** [comment]
honestly, looking into `archive` library, i don't see anything upfront - it may be deep hidden bug :( i don't have resources to fix this now, sorry

will add some more description on unzipping manually in the readme soon

**Comment by TheLastGimbus** [comment]
hey guys, small idea - could you try this with `.tgz` takeout format?

**Comment by TheLastGimbus** [comment]
# Well well well

I've just spent ~6 hours learing Rust just to get my dreams ruined by: https://github.com/dart-lang/sdk/issues/47718

I won't tell people to download another zip with my .exe and other .so for the Rust zip, so looks like we stick with Dart one




...or just migrate *the whole thing itself* to Rust :eyes: :thinking: :thinking: :thinking:

**Comment by TheLastGimbus** [comment]
i tested this a bit on windoza, and it turned out to lose **1/4** of my photos ;_;

so i disabled it for now in fede9a1b :(

**Comment by TheLastGimbus** [comment]
Will re-open if i ever bring the `archive` package back
