### ISSUE TITLE
limited by space in /tmp

### ISSUE THREAD

**Issue by rebelga** [TheLastGimbus/GooglePhotosTakeoutHelper#179]
My root partition has /tmp with 100GB free.  The work area for gpth is a couple TB, but it fails because the root becomes full (bad in general, of course).

I temporarily symlinked /tmp elsewhere as a work around, but this should be handled more elegantly.

**Comment by TheLastGimbus** [comment]
Can you show me some more detail about your takeouts etc? What's the largest file in the whole pack

**Comment by TheLastGimbus** [comment]
So you just don't have free space on disk 🤨🤨 ?

Again, more details - did you use interactive? Show the console output etc

**Comment by TheLastGimbus** [comment]
This is another issue with `archive` package :/ 

i won't address this myself nor now, but i may just migrate to some rust zip library in future

sorry for inconvinience!

**Comment by TheLastGimbus** [comment]
Will re-open if i ever bring the `archive` package back
