### ISSUE TITLE
Old Takeout made in 2019

### ISSUE THREAD

**Issue by LPFchan** [TheLastGimbus/GooglePhotosTakeoutHelper#182]
![explorer_XyETriJ1SV](https://user-images.githubusercontent.com/1547081/221855142-efa47e4c-2a20-4adf-9ba2-edcad1d67598.png)

```
PS C:\Users\(...)> C:\Users\(...)\Downloads\gpth-windoza.exe -i "D:\(...)\Takeout 2019-07-28" -o "D:\(...)\output2" --divide-to-dates
Okay, running... searching for everything in input folder...
Found 0 photos/videos in input folder
...oh :(
...
I couldn't find any D: reasons for this may be:
  - your Takeout doesn't have any "year folders" -
    visit https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper
    again and request new, correct Takeout
After fixing this, go ahead and try again :)
```

I have a takeout made (and unzipped) back in July 2019, but `gpth` doesn't detect anything from this folder. Seems like it has a different folder structure from current takeouts. Would there be any way I could make this work with older takeouts? (I haven't tried running `gpth --fix` just yet)

**Comment by TheLastGimbus** [comment]
BEST would be to re-export again

But if you have absolutely no way to do that, you'll need to use veryy old v1.2.0 version

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/releases/tag/v1.2.0

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/v1.2.0/README.md

**Comment by LPFchan** [comment]
I've already re-exported the thing from Google just few days ago, ran the `gpth` and it did wonders!👍 Just wanted to make sure if I'm not missing anything from the old 2019 takeout before yeeting them off my hard drive for good. I'll try the python version, thank you for everything!
