### ISSUE TITLE
Unable to run on mac

### ISSUE THREAD

**Issue by wudstrand** [TheLastGimbus/GooglePhotosTakeoutHelper#189]
When I try to run via the command line I get an error from MacOS.

### Error
```
“gpth-macos” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.
```

**Comment by wudstrand** [comment]
Figured this out.

https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by TheLastGimbus** [comment]
this might be important - did you try to run by double pressing or something? how did you do it finally?
