### ISSUE TITLE
Instructions for MacOS

### ISSUE THREAD

**Issue by palijn** [TheLastGimbus/GooglePhotosTakeoutHelper#192]
Since you deliver a gpth-macos executable that is unsigned, MacOS will complain when running it from the command line.
Maybe you can insert in the documentation that one can run `xattr -r -d com.apple.quarantine gpth-macos`  in order to bypass the signature check.

**Comment by TheLastGimbus** [comment]
Oh, interesting - noone reported that previously

can you show me the screenshot / mac versions etc of what is happening?

**Comment by palijn** [comment]
<img width="597" alt="Capture d’écran 2023-04-02 à 01 00 01" src="https://user-images.githubusercontent.com/33068030/229319897-3be4dd7c-6fe9-40c4-87e5-6257dd2a590a.png">

Sorry, this is in French. Basically, it says Apple cannot verify it does not contain any malevolent software, and the software must be updated. MacOS 13.3 . That must have happened on all MacOS versions since the introduction of Gatekeeper.
