### ISSUE TITLE
PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub

### ISSUE THREAD

**Issue by ssarfaty** [TheLastGimbus/GooglePhotosTakeoutHelper#194]
getting this on when running the tool:

Guessing dates from files : ███████████████████████████████████████. 56105/56639
Finding albums...
Moving photos to output folder : ██████████████████████████████████████.. 54742/56639  Creating shortcut for 20221206_110837.jpg in 12 failed :(
PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub:

**Comment by TheLastGimbus** [comment]
Currently i have no solution for that :( - gpth will just copy the file instead of making a shortcut and you should be good 👍

**Comment by ssarfaty** [comment]
oh ok, so no bigy .... 

is there a way i can help in debugging this for you ?

**Comment by TheLastGimbus** [comment]
hmm, you can send me screenshot of what names did the photo and the album have

my current suspicion is that powershell fails with non-ascii names, like ę ą etc, but yours seem to be pure-numbers :thinking:
