### ISSUE TITLE
Stuck on "Finding Albums... "

### ISSUE THREAD

**Issue by jarch123** [TheLastGimbus/GooglePhotosTakeoutHelper#199]
Yo,

Just wanted to say that I appreciate the work you have put into this! 
After extracting the photos and getting your program started, it goes through pretty much every .mp4 file stating that it "Can't get date" and then "Guessing dates from files"

Then when it gets around 80% done with the .mp4 files, it stops and says "Finding Albums" and gets stuck at that step, and I can't seem to figure out what to do after that.

Again, much appreciated, I'm sure that I am doing something incorrect.
I have attached a screenshot of the terminal when I get to the point.

Thank you
![Screenshot](https://user-images.githubusercontent.com/38747853/232320115-104ebc09-dd24-4544-824a-c1502741dd89.png)

**Comment by jarch123** [comment]
Just kidding, I am dumb, just needed to wait longer. My bad

**Comment by TheLastGimbus** [comment]
Haha 😅 i will add some "it can take some time" since this is only step that doesn't have a progress bar...
