### ISSUE TITLE
Question - Help Needed

### ISSUE THREAD

**Issue by Lindsay0385** [TheLastGimbus/GooglePhotosTakeoutHelper#2]
Hi - I joined Github just so I can send you a message, so I hope you see this.  I'm attempting to use Google's Takeout for backing up my photos.  With my frustration and googling, I found your code that could help me with combining into one folder and getting the correct dates on the files, only if I understood now to use it.  Besides being able to make my way through understanding VBA and HTML codes, I'm clueless with actual coding.  I see your instructions, but I do not understand past downloading your file and making sure there are only numbered folder.  For example, what does step 2 mean? Do I type step 4 in Terminal?  If so, how exactly do I type it?  Is there any chance you could send me step by step instructions for the coding illiterate?  If not, I understand, but I'd figured it didn't hurt to ask as it would be AMAZING if I got it to work.  I'm on a Mac running 10.10.3 and confirmed I have Python 2.7.6 installed.  Thank you so much for taking the time to read this! Lindsay

**Comment by TheLastGimbus** [comment]
Sorry for no response, I must've missed email notification or something.

To use this script, you need basic, like *really* basic knowledge on how to run Python in cmd:
First, you need to install it - find yourself in google how to install Python on Windows/whatever you are using. Then open cmd/terminal, `cd` to folder where my script is, and run "step 2" - it installs all required python libraries. Then you just run step 4, where you need to type in the path to your photos and folder where the output will be.

That's it!

**Comment by Lindsay0385** [comment]
Thank you so much for replying.  I guess I'm missing that really basic knowledge, hahaha.  But I'm going to attempt this later this weekend.  I'm on Mac which has Python installed.  Do I need to unzip the files I downloaded from Takeout first? I have 22 files about 10 GB a piece.  I really appreciate your help! Thanks, Lindsay

**Comment by TheLastGimbus** [comment]
You need to unzip all stuff you got from google and put everything in one big folder containing only "date folders" - everything else is in readme or will print out while running the program

**Comment by Lindsay0385** [comment]
Thank you so much! I can't believe I actually got the script to run.  It's running right now.  When I first tried to run it, Terminal said there was an error on Line 268 that prevented it from running, specifically this line..." print(f'No exif for {file}') " I deleted the f and than it ran.  I have about 250 gb of photos from Takeouts to organize with the script, so I'm sure it is going to take a while to run.  The hardest part was figuring out in which folder to install piexif, but somehow I got it to work. I ended up putting it in many locations and hoping one was correct, lol.  I wasn't sure how to add the option to divide into folders by year and date, but I can do that easily after.  Again, thank you so much for this script and your help! -Lindsay

**Comment by TheLastGimbus** [comment]
> I deleted the f and than it ran

Then it means you probably had old Python. Updating it would probably fix it (hope you won't stumble on more errors because of that - it's not the only place where i used `f''` :grimacing: )

>  The hardest part was figuring out in which folder to install piexif

It's standard pip library that you need to install by just typing `pip install piexif` (or `pip3`). Or, how I typed in readme: `pip install -r requirements.txt` (sorry, it was missing `-r` before).

> I have Python 2.7.6 installed

Oh crap I've just read that (probably because you edited it). That's why `f""` doesn't work. Then the rest of the script won't work either.

You need to:
1. Install Python 3 (three!)
2. Install pip3 if it's not already.
3. `pip3 install -r requirements.txt` just like in readme
4. Then run the script

**Comment by Lindsay0385** [comment]
Thankfully, I did install Python 3 before I started.  I ran the script as "python3 takeout_helper.py -i (FOLDER) -o (FOLDER)". That should work, right?  I had to start the script again as I didn't realize I had some folders in the format "2016-03-05-06", many actually.  So I went through and fixed those.  I'm not sure why Google named those folders that way.  I think I have pip3 installed correctly, but I can't check unless I stop the script from running.

**Comment by TheLastGimbus** [comment]
> but I can't check unless I stop the script from running.

You can just open new terminal

> in the format "2016-03-05-06",

Actually, my script takes first 10 characters to interprate date, so anything "YYYY-MM-DD-blablablaSomeGibbereish" will do fine

I'm honestly curious how well will it work with such a big collection - i only tested it on mine, ~1000 photos

**Comment by Lindsay0385** [comment]
Oh, that's good about the number of characters!  I didn't realize I could have more than one terminal window open, lol. I confirmed the requirement.txt was installed correctly.  I tried installing again and it said it was already installed. 

It stopped again at the exact same photo, which makes sense since it wasn't a folder naming issue..  Here's the error I get: 
```
~/_20170111_202123.JPG
time data '2017-01-10 22:44:21' does not match format '%Y:%m:%d %H:%M:%S'
==========!!!==========
You probably forgot to remove 'album folders' from your takeout folder
Please do that - see README.md or --help for why
Once you do this, just run it again :)
```

I moved that photo out of the folders and I'm trying to run it again. Crossing my fingers! :)

**Comment by TheLastGimbus** [comment]
Hm, can you paste more of what was printed? Was this photo in normal folder, or what do you think could be wrong with it?

**Comment by Lindsay0385** [comment]
Here's what was before it.  There was nothing after it, other than me starting the code over again.  I have no idea what was wrong with it.  The script is still running it's in the 2019 folders now, where it stopped in 2017 twice before at that same photo.  Could it be that it began with an underscore? It is in a normal folder.  

```

/Volumes/Seagate 4TB/Google Takeout Downloads/COMBINED/2016-12-18 #2/IMG_20160227_195503.jpg
/Volumes/Seagate 4TB/Google Takeout Downloads/COMBINED/2017-01-11/_20170111_202123.JPG

time data '2017-01-10 22:44:21' does not match format '%Y:%m:%d %H:%M:%S'

==========!!!==========
You probably forgot to remove 'album folders' from your takeout folder
Please do that - see README.md or --help for why

Once you do this, just run it again :)
==========!!!==========
```

**Comment by Lindsay0385** [comment]
Well, it stopped running, but nothing is in the output folder.  Here's what it ended with...
```
/Volumes/Seagate 4TB/Google Takeout Downloads/COMBINED/2020-07-18/._VID_20200718_165753.mp4
Given file is neither JPEG nor TIFF.
No exif for /Volumes/Seagate 4TB/Google Takeout Downloads/COMBINED/2020-07-18/._VID_20200718_165753.mp4
Couldnt find json for file :/
Last chance, coping folder name as date...
Couldnt insert exif!

/Volumes/Seagate 4TB/Google Takeout Downloads/COMBINED/2020-07-19/IMG_20200719_204053.jpg
Traceback (most recent call last):
  File "takeout_helper.py", line 345, in <module>
    for_all_files_recursive(
  File "takeout_helper.py", line 100, in for_all_files_recursive
    for_all_files_recursive(file, file_function, folder_function, filter_fun)
  File "takeout_helper.py", line 103, in for_all_files_recursive
    file_function(dir, file)
  File "takeout_helper.py", line 277, in fix_metadata
    set_file_exif_date(file, date)
  File "takeout_helper.py", line 248, in set_file_exif_date
    piexif.insert(piexif.dump(exif_dict), file)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/piexif/_dump.py", line 74, in dump
    gps_set = _dict_to_bytes(gps_ifd, "GPS", zeroth_length + exif_length)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/piexif/_dump.py", line 335, in _dict_to_bytes
    length_str, value_str, four_bytes_over = _value_to_bytes(raw_value,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/piexif/_dump.py", line 193, in _value_to_bytes
    value_str = (_pack_byte(*raw_value) +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/piexif/_dump.py", line 162, in _pack_byte
    return struct.pack("B" * len(args), *args)
struct.error: ubyte format requires 0 <= number <= 255
```

**Comment by TheLastGimbus** [comment]
No no no, don't delete jsons just yet! I really want to figure out what went wrong and fix it. Leave the "input folder" as you got it, and we will figure everything out step by step

The error seems to be because it failed to insert exif data in some file, aspecially the GPS. I will try to look at that and maybe add a try-catch to just print "error" without stopping the script

**Comment by Lindsay0385** [comment]
Hello again - I definitely didn't do anything yet.  Would you like to see the entire code?  I'm not sure how many characters this field can handle, but I can email it to you as well.  Looks like most of the .mp4s in the folders had the error "couldn't insert exif!". Let me know! I truly appreciate your help!

**Comment by TheLastGimbus** [comment]
I made try-catch in `piexif.insert` catch all exceptions, so it shouldn't cause trouble now - we will see if anything else won't. Try to run it now (with newest version of script)

(btw, I'm begging for some better exif library, which would support videos etc :pray: )

**Comment by Lindsay0385** [comment]
Awesome, thank you! I'll try it again when I have some free time, maybe tomorrow night or this weekend.  

That would be awesome if videos could be supported in the future!  Once again, I appreciate the help!

**Comment by TheLastGimbus** [comment]
You aren't supposed to edit anything in the code to use any functions

Python has a nice way of telling the program what you want to do in terminal by such `-s --something` flags. Some of them are providing some data, like `--input /path/to/input/folder`, and some of them are just flags that indicade true/false, like `--divide-to-dates`. You can do `takeout_helper.py --help` to see all of them

**Comment by TheLastGimbus** [comment]
By the way, I uploaded this project on Python Package Index - what that means to you, is that you can easily update and run it, see new README on how ;)

https://pypi.org/project/google-photos-takeout-helper/

**Comment by Lindsay0385** [comment]
I download the new package and ran it overnight. It worked perfectly! I have 35,423 (225 gb) of correctly dated and organized photos. Thank you so much! I truly appreciate it!

**Comment by TheLastGimbus** [comment]
Nice! I'm also very glad that it actually helped you ❤️

Now, watch out if you will want to move them to your Android (as I wrote in readme), it's really easy to lose modification date info 👍

**Comment by Lindsay0385** [comment]
That is good to know! Thank you again!! 😄
