### ISSUE TITLE
came across reddit, awesome :)

### ISSUE THREAD

**Issue by xujiaxi-ucb** [TheLastGimbus/GooglePhotosTakeoutHelper#209]
I'm planning to use it for my Google Photos. Does this metadata helper write the photo's location/GPS from the JSON file into the image? I saw the todo, but I wonder if you meant that.

**Comment by TheLastGimbus** [comment]
Sadly no :( - if you modified a lot of photo locations in photos app, this is missing currently - otherwise they should be in photos exif metatada already
