### ISSUE TITLE
date-unknown Folder

### ISSUE THREAD

**Issue by migben01** [TheLastGimbus/GooglePhotosTakeoutHelper#213]
I´ve used your script and it worked for 80 % of my images
However the remaining 20 % ( around 13 000 images ) were put on a folder called date-unknown.
It seems the script was unable to associate the existing Json file to those images. How can i fix this?
What´s the best way to retrieve the metadata to this images so they can be sorted with the right date automatically?
thanks

**Comment by TheLastGimbus** [comment]
Hi! Try to find corresponding jsons to those images and show them here - then we can try to figure out how can we match them automatically :eyes:

Even if there are no jsons for them anyway, we can try to guess their dates from their name
