### ISSUE TITLE
The script seems to stop at "Finding albums..."

### ISSUE THREAD

**Issue by jerrellmardis** [TheLastGimbus/GooglePhotosTakeoutHelper#215]
When I run the script in unraid it stops every time at "Finding albums". I'm using the following command
`./gpth-linux --input <input_directory> --output <output_directory>`

**Comment by TheLastGimbus** [comment]
The finding albums doesn't have progress bar because i didn't quite know how to implement it, and it can take some time, but it should finish unless whole program crashes - wait patiently and try to watch cpu usage - it should be high while finding...

**Comment by jerrellmardis** [comment]
Yep that was it..it just took a little bit of time. Thanks.

**Comment by TheLastGimbus** [comment]
I may add some print message about this in next release, thx for being awake :eyes:
