### ISSUE TITLE
Error with some file names

### ISSUE THREAD

**Issue by Sappstal** [TheLastGimbus/GooglePhotosTakeoutHelper#217]
Thanks for this awesome tool, you managed to fix more than 14k pictures! However, seems like is unable to deal with these formats: 
```
- IMG-20208513-WA0042-ha editado.jpeg

- 2021-05-22 23.19.26-ha editado.jpeg
```
This only affects to like 13 files, but why is happening? 
BTW "ha editado" translates to "has edited" in English

**Comment by TheLastGimbus** [comment]
What do you mean by unable to deal? It told you that it coulnd't find date?

Okay, so by this, it means that it couldn't find their jsons, read date from exif nor guess from name. We will try to resolve cases for both json and names

could you please try to find and show here corresponding non-edited jpg, and it's json, etc - it's name, location, maybe json content too

we will try to add "ha editado" to "extras list" that will then look for same pics but without  "edited"

**Comment by Sappstal** [comment]
Hi! yeah the error said that it couldnt guess the date.  Seems like there is a json missing? Check the image below.

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/88688508/12a91ac5-2cf7-4aa7-8ff3-a7579d9e2f89)

**Comment by TheLastGimbus** [comment]
@Sappstal could you check out the pr?

**Comment by TheLastGimbus** [comment]
@Sappstal could you check out the pr?

**Comment by TheLastGimbus** [comment]
@Sappstal could you check out the pr?
