### ISSUE TITLE
Exif data not found for 7k+ files even though json mapping files exist

### ISSUE THREAD

**Issue by jerrellmardis** [TheLastGimbus/GooglePhotosTakeoutHelper#218]
First off, thank you for creating this. I downloaded roughly 1.2TB worth of data using Google Takeout but unfortunately the exif data for roughly 7k+ of those did not map over and are now in a `date-unknown` directory. Additionally, I've found corresponding json files for some of these unmapped files and some of the files even have the date in their name. Also it seems that a lot (maybe all) of my MP4 files were not mapped.

Is there anyone to reprocess just these files? I saw the `--files` command but I'm not sure how to use that being that I've already processed the files from the Takeout directory.

![Screenshot 2023-06-28 at 6 47 16 PM](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/78137/24331add-e288-4641-ab8b-a7306da9765e)

**Comment by TheLastGimbus** [comment]
hi!

can you please show where and how you found corresponding jsons to those photos? we will try to guess why gpth did not find it...

**Comment by MeisterEdero** [comment]
Hi, 
first of all thank you very much for creating this tool. 

I'm not sure, but I guess I've kind a like a similar problem. I used the latest version [v3.4.1] and selected the duplicate-copy option. In the result "ALL_PHOTOS" folder i got a "date-unknown" folder. I checked some of the pictures and the some of the dates are missing in the the picture allthough the information are in the .json file. I checked it on Google Photos and the photoTakenTime is visible there but not in the settings menu of the picture as you can see in the screenshot. It now has the creation date of the day when I ran this tool. I know this picture got sent to me through Whatsapp, but it still has the information in the .json. 

May you can help me please?

![grafik](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/140701925/b17e6ec8-d5d5-46a5-884f-c7a26802272f)

**Comment by hTepAchtetepe** [comment]
Hello @TheLastGimbus , first thanks for your work, it's amazing.

I don't know if I can re open this issue but I can see files (Movie espacially) in date-unknown folder while there is a json file with date.
Here are details.


<img width="758" alt="Image" src="https://github.com/user-attachments/assets/369ba34e-ad0d-4b95-8844-e8b1048e31e1" />
<img width="775" alt="Image" src="https://github.com/user-attachments/assets/74b62b27-134f-415b-aed9-a6cdae1fde60" />

<img width="688" alt="Image" src="https://github.com/user-attachments/assets/a264fe27-b728-456b-9c42-02670dac709a" />

**Comment by TheLastGimbus** [comment]
ohh, okay... looks like same as #353 - watch there for updates on that, thanks for reporting :+1:
