### ISSUE TITLE
Script skipped .MTS files

### ISSUE THREAD

**Issue by WeGoToMars** [TheLastGimbus/GooglePhotosTakeoutHelper#223]
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/47947772/391997f1-bc8c-4adb-ac7c-04c28920d623)

`.MTS` files seem to be skipped during transfer. I also checked the year/month folder they were supposed to be in, and they aren't there. 

I'm not sure whether you do any filtering by format, but here is the mediainfo for one of the files. They are just MPEG-4 files recorded on a mid-2010s Sony camera.

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/47947772/d0b8f590-5991-4994-8cfd-b0f4f7e2680d)

On the other hand, it worked great for the pictures, so thank you!

**Comment by TheLastGimbus** [comment]
On it...

**Comment by TheLastGimbus** [comment]
No response from repo owners - reaserarched a bit more and, jeez

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/40139196/4ad4b498-d0a0-4d21-bc17-fbdb210ae070)

Seems like this is wide problem because Apache decided to put it like this in their db and everyone uses it 🙃
