### ISSUE TITLE
version: 3.4.1 maintains duplicates in output folder

### ISSUE THREAD

**Issue by jonno85** [TheLastGimbus/GooglePhotosTakeoutHelper#231]
On macOS,
launching **gpth** and selecting the default cases, produces the output folder in which the **ALL_PHOTOS** folder contains the original file and the augmented file with the metadata packaged and the suffix `-edited`.
Shouldn't the original file be removed? or at least have a menu option to maintain it?
When it is time to upload to Synology, the different name won't be recognized as a duplicated file.

**Comment by jonno85** [comment]
thanks @TheLastGimbus for the quick answer.
Yes the checksum is different and I guess the metadata are merged into the file. My need is, considering that you want to drag the output folder into **Synology**, then I need to avoid the original file, otherwise it will show duplicated pictures. Unfortunately, Mac Finder doesn't allow me to negate the search and easily remove all the original **not -edited** files.
Is it more clear?

**Comment by TheLastGimbus** [comment]
here you go buddy

```python
import os
import shutil

for f in os.listdir():
  if '-edited' in f:
    og = f.replace('-edited', '')
    print('to rm:', og)
    # uncomment this to actually run
    # os.remove(og)
    # or, safer one - create a "to-rm" directory beforehand
    # shutil.move(og, 'to-rm')
```

would be grateful for a small donate :wink:

**Comment by TheLastGimbus** [comment]
may re-open in future in any case people *really* want skipping the original non-edited photos...
