### ISSUE TITLE
MOV Couldn't insert exif! and other errors

### ISSUE THREAD

**Issue by nbourg8** [TheLastGimbus/GooglePhotosTakeoutHelper#24]
![test_folder_sub](https://user-images.githubusercontent.com/24832335/101232825-b9bc4c00-3679-11eb-9141-fc59afd7a548.PNG)
MOV files are not updating the date/time.

Background:
Windows 10 w/Latest Updates
Backup taken from Google Takeout on 12/1/2020 of ALL Google Photos, Including Albums
All files unzipped to a common directory
Album folders deleted (including contents)
Only folders remaining are of yyyy-mm-dd naming convention and left unchanged from their original zip extraction
Installed Python3 including PATH updates
With administrator command prompt, ran "pip3 install -U google-photos-takeout-helper" without issue
With administrator command prompt, ran "python3 -m google_photos_takeout_helper -i c:\test -o c:\testout"

I got a ton of errors, no MOV files were updated.
Screenshots and logs are attached. Please help.
![cmd_capture](https://user-images.githubusercontent.com/24832335/101232781-5f22f000-3679-11eb-9500-6debb4737caf.PNG)
![test_folder](https://user-images.githubusercontent.com/24832335/101232783-5fbb8680-3679-11eb-8df4-8c00ae45e180.PNG)
![testout_folder](https://user-images.githubusercontent.com/24832335/101232784-5fbb8680-3679-11eb-91ce-172100556e03.PNG)
[date_from_folder_name.txt](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/5646438/date_from_folder_name.txt)
[failed_inserting_exif.txt](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/5646439/failed_inserting_exif.txt)

**Comment by nbourg8** [comment]
This is a moot point now that I realize Google Takeout actually has this information in the metadata. Sorry for the uneducated post. My Gallery program was able to sort it out by date taken and last modified.

**Comment by bitsondatadev** [comment]
@nbourg8 can thus be closed then?

**Comment by TheLastGimbus** [comment]
It's a weird thing that pretty much no exif library supports exif inside videos, but a lot of them do have it... 

But don't worry, if the video had it originally, those from takeout should have it too
