### ISSUE TITLE
GPTH Doesn't change the date created, but the date modified

### ISSUE THREAD

**Issue by Beerandoo** [TheLastGimbus/GooglePhotosTakeoutHelper#241]
This is issue to my knowledge occurs on windows 10 home. I have noticed the date created is the date that the original picture was merged with the json file from google takeout, and the actual date the file was created is put on the date modified. This makes it so that it actually doesn't sort by date correctly whatsoever. 
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/137313823/dc814f27-ad3a-4ced-abdc-21ca6dfcb666)

**Comment by TheLastGimbus** [comment]
pffffffff... yeah...

You see, i don't have such an option in Dart language :sob:

i decided that this is good enough, sicnce you can still select "sort by last modified" in your file explorer, and most people have it like that by default...

sorry for inconvinience :/
