### ISSUE TITLE
Can't get dates on -modifié files

### ISSUE THREAD

**Issue by palijn** [TheLastGimbus/GooglePhotosTakeoutHelper#243]
Hi,
sorry, me again !
Taking out for a friend now.
GPTH complained it could not find a date on, well, the now well-known and dreaded -modifié files. 412 of them, that's 10% of the 4169 files. And more importantly, I won't move them one by one like the last time when there were a dozen.
Running GooglePhotosTakeoutHelper v3.4.2 on MacOS.

One example :  

`Can't get date on /Volumes/Macintosh HD/Users/<redacted>/Takeout/Google Photos/Photos from 2014/08-21-07_1547-modifié.jpg`

`% ll "/Volumes/Macintosh HD/Users/<redacted>/Takeout/Google Photos/Photos from 2014/08-21-07_1547"*`
`-rwxr-xr-x@ 1 <redacted>  <redacted>  827 14 sep 05:44 /Volumes/Macintosh HD/Users/<redacted>/Takeout/Google Photos/Photos from 2014/08-21-07_1547.jpg.json`

File 08-21-07_1547.jpg.json attached to this issue. _(Added .txt extension because wtf github?)_
[08-21-07_1547.jpg.json.txt](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/12622415/08-21-07_1547.jpg.json.txt)

The whole list of the problematic file is attached here, too : 
[gpth-cant-get-dates.txt](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/12622416/gpth-cant-get-dates.txt)

As last time, I wonder, shouldn't GPTH be able to guess the dates from the filenames even if it missed the JSON? 08-21-07_* looks quite obvious, doesn't it ?

**Comment by palijn** [comment]
@TheLastGimbus do you want me to provide the Takeout archive ? It's only less than 5GB.

**Comment by TheLastGimbus** [comment]
Oh, if that's not a problem then this would 9850284x times speed up this for me

You can send me some link on my priv Discord - find me on the freebuddy server: https://discord.gg/fYS98UE5Cu

**Comment by palijn** [comment]
Have you had any chance to work on the issue yet ? :)
