### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by TheLastGimbus** [TheLastGimbus/GooglePhotosTakeoutHelper#25]
So right now, the script just prints every file while fixing it's metadata, and when something bad happens, the last printed path is the photo that caused problem

My idea: wrap `fix_metadata` in a `try-catch all`, then inside `catch` print the photo path and *then* re-throw previously caught exception (because dummly catching and ignoring all exceptions would be bad)

Also adding progress bars to removing duplicates and coping would be nice

**Comment by jmigual** [comment]
If you want to add a progress bar you may want to take a look at https://github.com/tqdm/tqdm

**Comment by conradstorz** [comment]
I'll be happy to add the try/except wrapper you described if you like what I have proposed for the use of tqdm in my pull request.
