### ISSUE TITLE
PowerShell doesnt work :( - report that to @TheLastGimbus

### ISSUE THREAD

**Issue by atillabayrambas** [TheLastGimbus/GooglePhotosTakeoutHelper#257]
Hi,

Thanks for your time and effort making this tool. I hate the fact that Google doesn't implement a feature for this. You are a life saver!

I have run into a unkown problem. While using your tool I am getting this error at the end. Do you know what this means?

```
_PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub:

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues

...or try other album solution
sorry for inconvenience :(
 - coping normal file instead
Moving photos to output folder : ████.................................... 1269/10540  Creating shortcut for 2023-08-12(10).jpg in Copy of Atilla failed :(
PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub:

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues

...or try other album solution
sorry for inconvenience :(
 - coping normal file instead
Moving photos to output folder : ████████████████████████████████████████ 10540/10540
========================================
DONE! FREEEEEDOOOOM!!!
Skipped 85 duplicates
Couldn't find date for 818 photos/videos :/_
```

**Comment by TheLastGimbus** [comment]
Hi! Thanks for reporting, but i think i cannot do much about it :confused: windoza powershell is too confusing

> Creating shortcut for 2023-08-12(10).jpg

problem mayyy seem to be with the `()`

Try other album solution or just accept that some of your albums will contain originals and not shortcuts
