### ISSUE TITLE
gpth-windoza when press enter, doesn't get the open dialog box

### ISSUE THREAD

**Issue by labba** [TheLastGimbus/GooglePhotosTakeoutHelper#258]
i'm on windows 11 Version	10.0.22621 Build 22621, when i run the gpth-windoza.exe v3.4.3 and getting to the meesage of "[press enter to continue]" to get the takeout folder, after pressing enter the dialog box doesn't appears.

only after entering a char and then pressing enter the dialog box appears. for example pressing "1" and then enter.

**Comment by TheLastGimbus** [comment]
I am semi-aware of this... the pop-ups don't always pop up smoothly etc - i don't know how to resolve this for now, and this probably needs to await if full-blown ui app ever comes out
