### ISSUE TITLE
Google Takeout no longer exports metadata as JSON? 

### ISSUE THREAD

**Issue by NoahFiner** [TheLastGimbus/GooglePhotosTakeoutHelper#262]
Hey thank you so much for this script! I tried a Google Takeout back in July and got stuck migrating my photos due to the metadata separation when I hadn't found this tool yet. 

I tried creating a new takeout yesterday, but it looks like my exported Google Photos results no longer have JSON files.

<img width="1280" alt="Screenshot 2023-11-18 at 10 46 54 AM" src="https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/10334304/07257b4b-1246-42f0-92c3-e16f01c60176">

Additionally, I confirmed via https://jimpl.com/ that my exported photos now have their appropriate capture dates attached. 

<img width="1289" alt="Screenshot 2023-11-18 at 10 48 11 AM" src="https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/10334304/9c6f1264-4d1f-4985-8d33-266c5e14209c">

I couldn't find any information about this online but I was able to reproduce through multiple takeouts. Did Google fix this horribly annoying step of their migration process?

## The issue with the script

Anyways, the script now logs `Can't get date on ...` for every photo. 

<img width="564" alt="Screenshot 2023-11-18 at 10 49 46 AM" src="https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/10334304/30a93330-ce61-4b6e-900e-b07a88c5f5d0">

I'm still hoping to utilize this script for organizing my photos into folders by their capture date instead of being separated into many separate folders. Would it be possible to update the script to also check for if the photo already contains its capture date in its already existing metadata? Thank you!

**Comment by mb-dev** [comment]
I have the same issue

**Comment by aviv926** [comment]
Your photos look like they came from a professional camera, it could be that the information is embedded in them so that there is no need for JSON
Can you tell where the pictures were uploaded to Google Photos?

**Comment by NoahFiner** [comment]
@TheLastGimbus that was it!!!!!! Thank you for all the help and debugging

<img width="553" alt="Screenshot 2023-12-05 at 9 53 37 PM" src="https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/10334304/dc71d6c4-3892-49e9-8379-bb4a4b5ab27a">

**Comment by TheLastGimbus** [comment]
Okay so that's a +1 for me to resolve #203 some day

happy it works!
