### ISSUE TITLE
Feature Request: output folders by year (no month)

### ISSUE THREAD

**Issue by niesfisch** [TheLastGimbus/GooglePhotosTakeoutHelper#264]
hi,

first of all. thank you for this awesome tool!

there is currently this flag, which outputs folder by year and month.

`--divide-to-dates        Divide output to folders by year/month`

i would like to be able to put all pictures into a year folder without separating them by month. a switch would be perfect where i can decide via command line flag what i want.

thanks a lot and best regards
marcel

**Comment by TheLastGimbus** [comment]
Umm, i don't think i will add this cause there will be too many options to choose

...but, i made a separate mini version of gpth that does just that - download it here: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/actions/runs/7089472516

**Comment by niesfisch** [comment]
thanks a lot for this and keep up the good work!
