### ISSUE TITLE
"powershell doesn't work."

### ISSUE THREAD

**Issue by troaphy** [TheLastGimbus/GooglePhotosTakeoutHelper#277]
<img width="597" alt="image" src="https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/96665071/a7f3f98a-747f-4993-84f6-bcac9146a1b8">

yeah so the screenshot - what does this mean, it just told me to report it

**Comment by TheLastGimbus** [comment]
Nice of you that you did! I will try to solve that some day with #249

for now, do as it says and either ignore those cases or use other album solution :+1:

**Comment by bersakosha** [comment]
I'm also experiencing this issue. :(
But if I understand correctly - when creation of symlink fails the file is just copied instead. So result is valid - no need to rerun this with another option.
