### ISSUE TITLE
Enforcing python version in setup.py

### ISSUE THREAD

**Issue by rddaz2013** [TheLastGimbus/GooglePhotosTakeoutHelper#28]
Please enforce python version 3.6 for the f-strings. 

`import sys
if sys.version_info < (3,6):
    sys.exit('Sorry, Python < 3.6 is not supported')`

thx

**Comment by TheLastGimbus** [comment]
Hm, isn't there some special setup property that's made for this? I'll check it - I didn't know that f-string are only >3.6, thanks!

**Comment by TheLastGimbus** [comment]
Closed in [this](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/commit/fec13dd54b2ce2fd67b09bafa3414cd3c655f578)

It will be present in next release (probably soon)
