### ISSUE TITLE
Feature: Option to include JSON no matter what

### ISSUE THREAD

**Issue by hecon5** [TheLastGimbus/GooglePhotosTakeoutHelper#280]
It would be nice if a JSON output was provided no matter what (like option 3 when deciding what to do with albums). If I've missed it, let me know!

**Comment by TheLastGimbus** [comment]
What would be the difference then besides... just leving the takeout as-is? Fixed last-modified dates?

If think you can achive what you want with something like: 
1. Use gpth with one-big-folder mode
2. Find all .json files in og takeout (with windows file explorer or something, or terminal)
3. Select all and copy to output folder - `cp **/*.json output/folder/`


Sounds good?

**Comment by MadeByPP** [comment]
I feel like this refers to the Takeout feature of Google Photos.

**Comment by TheLastGimbus** [comment]
Yeah no response or explanation so closing for now, but feel free to write again
