### ISSUE TITLE
Unexpected Behavior in gpth-windoza.exe v3.4.3

### ISSUE THREAD

**Issue by BoBBer446** [TheLastGimbus/GooglePhotosTakeoutHelper#283]
**Description:**
I've noticed an issue with the gpth-windoza.exe version v3.4.3. When I run it, instead of opening the PowerShell, it opens the Terminal app. Additionally, when attempting to create albums, the application unexpectedly shuts down without providing any error messages or feedback.

**System Information:**
- Windows Version: Microsoft Windows 11 Pro
- Build: 10.0.22631
- .NET Framework Versions:
  - 2.0.50727.4927
  - 3.0.30729.4926
  - 3.0.30729.8795
  - 3.0.4506.4926
  - 3.0.6920.4902
  - 3.5.30729.4926
  - 3.5.30729.5003
  - 4.8.09032 (x6)
  - 4.0.0.0

**Additional Information:**
- Original files are located on an NVMe drive.
- The target folder for creation is on a USB 3.0 HDD.

**Steps to Reproduce:**
1. Download and install gpth-windoza.exe v3.4.3.
2. Run gpth-windoza.exe.
3. Attempt to create albums.

**Expected Behavior:**
- The gpth-windoza.exe should open the PowerShell.
- Album creation should proceed without errors.

**Actual Behavior:**
- The gpth-windoza.exe opens the Terminal app instead of PowerShell.
- While attempting to create albums, the application unexpectedly shuts down without providing any error messages or feedback.

This behavior is unexpected and may cause confusion for users who are expecting PowerShell to be launched. Please investigate and address this issue in the next release.

Thank you!

**Comment by TheLastGimbus** [comment]
> instead of opening the PowerShell, it opens the Terminal app

that's expected and okay

> The target folder for creation is on a USB 3.0 HDD.

look at #251 discussion

**Comment by BoBBer446** [comment]
I've successfully moved all my photos to the following directory on my G: drive: `G:\GoogleTakeout`. 

For instance, the photos from 2016 are located in `G:\GoogleTakeout\ALL_PHOTOS\2016`.

However, I've noticed an issue with the link targets for the pictures. They're incorrectly pointing to a path on my C: drive, like `C:\ALL_PHOTOS\2023\08\DSC00872.JPG`, instead of the correct new location on the G: drive, which should be `G:\GoogleTakeout\ALL_PHOTOS\2023\08\DSC00872.JPG`.

I'm concerned that if I copy these files to my Nextcloud, the photos will not be recognized correctly in albums due to this path discrepancy.

Can you provide guidance on how to correct the link paths to ensure my photos are properly located and displayed in Nextcloud albums?

**Comment by TheLastGimbus** [comment]
> if I copy these files to my Nextcloud, the photos will not be recognized correctly in albums

they will not be recognized anyways, since these are windows shortcuts - Nextcloud won't give a damn about it

> They're incorrectly pointing to a path on my C: drive

i know :/ #276 

> Can you provide guidance [...] Nextcloud 

no, since i don't use it, but your best guess is to use `duplicate-copy` albums option :+1:

**Comment by BoBBer446** [comment]
thx man! You're aweasome!
