### ISSUE TITLE
Apple Sidecar files (videos of Live Photos) in date-unknown

### ISSUE THREAD

**Issue by m1ndy** [TheLastGimbus/GooglePhotosTakeoutHelper#286]
Hi! Great script. I ran it on my Takeout archive of ~400k items (!) and it worked pretty well. About ~10k items are in the `date-unknown` folder within the `ALL_PHOTOS` folder.

The vast majority of these `date-unknown` files I notice are `.mp4` files that were part of a Live Photo taken from an iPhone. They are the sidecar files.

Any interest in doing special treatment for them so they take on the EXIF dates of their accompanying parent `.heic` or `.jpg` files?

**Comment by TheLastGimbus** [comment]
> Any interest

absolutely! In #180 issue - look up there. So closing this one as a duplicate
