### ISSUE TITLE
Virustotal detects "trojan" (6/72) on gpth-windoza.exe (3.43)

### ISSUE THREAD

**Issue by johnmhm** [TheLastGimbus/GooglePhotosTakeoutHelper#288]
https://www.virustotal.com/gui/file/a36ef8b546e381a05f47b2762bc17819148dbf9984e03ac979db3b2c4963d18d/detection

**Comment by johnmhm** [comment]
Zero detects on release v3.4.2

https://www.virustotal.com/gui/file/9d9e1577cafee4b25bfee61d0bbd41d3a12b1b03d2f4c23f6564dfe7a31430a4/detection

**Comment by TheLastGimbus** [comment]
# :shrug: 

Everything is open source, even the build pipeline - i have pretty much no way of uploading a virus here

**Comment by johnmhm** [comment]
Sorry for reopening the issue. I am in no way accusing you of anything, and have no reason to believe that you're up to anything nefarious. I just wanted to let you know that it was happening. I unfortunately also know that it can be a pain in the ass to get the detections resolved/removed. 

Your software saved me a lot of time - thank you for that.

**Comment by TheLastGimbus** [comment]
> I am in no way accusing you of anything

yeah yeah cool and everything, i'm just leaving notes to link to if anyone does

> I just wanted to let you know

thx for that, funny to know :D
