### ISSUE TITLE
PathNotFoundException

### ISSUE THREAD

**Issue by jestlin15** [TheLastGimbus/GooglePhotosTakeoutHelper#289]
<img width="994" alt="image" src="https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/112469727/b43291a7-ea6e-43c7-8d8f-a5a087c075b0">

Hi I faced this error. After the error I checked the image file _IMG_2423.JPG, it has already been moved to my output file with the date corrected for but the json file was still in the takeout folder. How do you recommend I move forward from here please?

**Comment by TheLastGimbus** [comment]
This is #203 - you will find help there :+1:
