### ISSUE TITLE
PowerShell doesnt work :( 

### ISSUE THREAD

**Issue by YousefMenesy** [TheLastGimbus/GooglePhotosTakeoutHelper#291]
Hi, first, thank you for creating this software! its amazing! 
i am getting this issue however: 
PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub
this when exporting using the shortcut option.

**Comment by TheLastGimbus** [comment]
Same as #257 - thanks for reporting :) i am aware and solution is on the horizon - but right now just use different album option :+1:

**Comment by YousefMenesy** [comment]
That is amazing! Thank you!
