### ISSUE TITLE
Nothing happens when run from the command line on Linux

### ISSUE THREAD

**Issue by VictorWesterlund** [TheLastGimbus/GooglePhotosTakeoutHelper#292]
Hi!

I'm unable to get version [3.4.3/gpth-linux](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/releases/tag/v3.4.3) to run on Debian. The program exists immediately when I run it from the CL. 

~~_I was, however, able to run version [3.2.0/gpth-linux](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/releases/tag/v3.2.0) without any issues. So there is that! Just thought I'd report it._~~
**EDIT:** Never mind! Version 3.2.0 starts but runs into an exception at the first interaction step. But I won't comment on this since it's an older version (unless requested).

I would be happy to provide more information but I couldn't find any logs for this program.

---

```sh
# lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/35688133/66f56999-a37d-4c19-b2c5-216791508001)

> Program exists immediately when run

**Comment by TheLastGimbus** [comment]
Huh weird. Can you try with `--help` ?

If still doesn't work, could you try to install dart and run the code directly https://dart.dev/get-dart ?

Maybe dart expects some `libc` stuff or whatever that you don't have on your pure-Debian system??


Ehhh... another sign to go for another full blazing-fast rewrite in Rust...

**Comment by VictorWesterlund** [comment]
Oh wow my apologies... it looks like the download of the binary messed up somehow - it's empty! You can even see it sitting there at 0 bytes on my screenshot 🤦

**Anyhow, I downloaded it again and it works fine now. Sorry!**

Thank you for still maintaining this. This tool just saved me hours of my time, will donate a few bucks!

**Comment by TheLastGimbus** [comment]
Cheers! Spend this time on tweaking your tiling wm or something :clinking_glasses: :penguin:
