### ISSUE TITLE
.exe detected as virus on VirusTotal

### ISSUE THREAD

**Issue by Sheeley7** [TheLastGimbus/GooglePhotosTakeoutHelper#296]
The .exe in the releases results in 6 detections on VirusTotal. You may consider doing what you can to eliminate this if its a false positive.

**Comment by BoBBer446** [comment]
Can you shre the hash ?
https://www.virustotal.com/gui/file/a36ef8b546e381a05f47b2762bc17819148dbf9984e03ac979db3b2c4963d18d

There is no Problem:
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/10163536/a0b7909d-1ba4-4ce8-8b61-3056aff0e605)

You can trust the global Players:
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/10163536/3169fcbc-5cf4-464f-b535-f4b315a7f411)
BitDefender
ClamAV
Avast
AVG
DrWeb
Microsoft
Sophos
Symantec

**Comment by TheLastGimbus** [comment]
Nope, i'm not gonna play cat-and-mouse with these :shrug:
