### ISSUE TITLE
not an issue, but no other way to contact

### ISSUE THREAD

**Issue by gosugimoto** [TheLastGimbus/GooglePhotosTakeoutHelper#3]
I've tried so many different scripts and settings and trying things myself...but this is the one that really worked for me!  Thank you so much for offering such a great script as open source.  You've made my day after so much wasted time!!
Thank you thank you thank you!!!!

**Comment by TheLastGimbus** [comment]
I'm really glad that I helped! You can always hit me up on Reddit or Twitter (with the same nick) or my email :+1:
