### ISSUE TITLE
Linux Mint: Program runnning but not moving files

### ISSUE THREAD

**Issue by dcolecpa** [TheLastGimbus/GooglePhotosTakeoutHelper#301]
I downloaded the code and gave the gpth-linux file execute permissions.  I run it and it requests an input folder and then an output folder.  Unfortunately, the files don't go anywhere from there.  

When I use the command line I get :

    gpth-linux: command not found
or
    Command 'gpth' not found, did you mean:
or
     bash: ./gpth: No such file or directory

Did I miss something or is there a way to troubleshoot?

**Comment by TheLastGimbus** [comment]
```bash
cd folder/with/gpth/exe
# the dot slash
./gpth-linux
```

**Comment by dcolecpa** [comment]
Thank you, that worked!
