### ISSUE TITLE
README.MD suggestion: running -AllDates<FileModifyDate might not always be safe

### ISSUE THREAD

**Issue by Zoomer1988** [TheLastGimbus/GooglePhotosTakeoutHelper#303]
Hi! First of all, thank you for the gpth! A very helpful tool.

While studying your readme, I noticed you suggest using the exiftool with -overwrite_original -r -P "-AllDates<FileModifyDate" "your/output/folder/ALL_PHOTOS/" parameters. I think it's somewhat destructive in nature since it'll overwrite the existing metadata date with file modify date. While it might be fine for a typical use case (user exported takeout > user unpacked everything > user ran gpth > user ran exiftool), it might do damage in case file modify date was altered along the way (e.g. user ran cp -r without -preserve before running the exif tool or some such). 

Maybe it'd be a good idea to recommend running exiftool -FileModifyDate<DateTimeOriginal before running "-AllDates<FileModifyDate"?

I mean, it still wouldn't be perfect as all the files without previously existing exif metadata would have some nonsense written, but still. Or maybe some sort of generic warning would be great?

It's just a thought experiment, I'm not complaining or anything :P

**Comment by TheLastGimbus** [comment]
turns out that exiftool, as always, has a solution to that :D

thanks!
