### ISSUE TITLE
Virustotal analysis: 5 vendors indicate that windows version has trojan

### ISSUE THREAD

**Issue by bloppernd123** [TheLastGimbus/GooglePhotosTakeoutHelper#304]
It might be false positives, but devs should probalby investigate, why the files are getting identified as trjoan:
https://www.virustotal.com/gui/file/a36ef8b546e381a05f47b2762bc17819148dbf9984e03ac979db3b2c4963d18d?nocache=1

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/124742494/a137560c-b723-4819-931c-cfb43c8a660f)

**Comment by TheLastGimbus** [comment]
Yeah of course gpth is a backdoor. Backdoor to freedom :sunglasses: 

dupliacate of #296
