### ISSUE TITLE
Cannot Access Other Drives In My PC

### ISSUE THREAD

**Issue by aminhusni** [TheLastGimbus/GooglePhotosTakeoutHelper#306]
The folder select dialog will only show your current C drive and desktop contents. 
All my files are inside another drive which I cannot access using the dialog. 

I hope this can be fixed. Probably just some permission problem. 
If not, allow for manual input of directory path. Thanks!

![Screenshot 2024-04-14 042938](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/8511047/4101c352-5d9e-49ba-aac6-384ce2cb03bf)

**Comment by TheLastGimbus** [comment]
> allow for manual input of directory path

It is possible, with cmd options. Just run gpth in cmd `gpth.exe --help`

It's weird that disks don't even show up in picker, but if they did, you would probably have problems with: #251 

(Closing this as duplicate)
