### ISSUE TITLE
I couldn't find any D: reasons for this may be:

### ISSUE THREAD

**Issue by hpsof** [TheLastGimbus/GooglePhotosTakeoutHelper#309]
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/da6886e7-6ca6-49e0-b8d3-cd9dfd54d61c)

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/056b8698-66c7-420d-a09c-284c3c115b79)

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/2bb92d31-a6e7-4ef0-b58c-cf7cf49ea7dc)

[tree_alltakeouts.cp850.txt](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/15272577/tree_alltakeouts.cp850.txt)
[tree_alltakeouts.txt](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/15272579/tree_alltakeouts.txt)

**Comment by hpsof** [comment]
what might be wrong? repeated the process with different settings and exports: always same message

**Comment by hpsof** [comment]
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/01a496ab-dcfb-45cd-bac5-85467212c68c)
stupid question: does this really match to one of my year folders?

would following not deliver a successful match ?
`
year-folder: takeout-20240509T051501Z-001
(19|20)\d{2} <== year any from 19[00] up to 20[99]
(0[1-9]|1[1,2]) <== month [00 to 12]
(0[1-9]|[12][0-9]|3[01])  <== day [01 to 31]
`

**Comment by TheLastGimbus** [comment]
Look at visual guide in README once again. You need to end up with just a single folder named "Takeout", with bunch of "Photos from ..." inside it

**Comment by hpsof** [comment]
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/d433f121-57f4-4f11-97d2-ea5aaccd9a95)

thats what i did, see above:
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/530c170a-f1cc-492e-a407-432d5e49110d)

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/4bdd3e67-a242-4aad-82a0-c78774dfdc47)

so i do not understand, whats not according to the instructions in the README ???

**Comment by hpsof** [comment]
oke. the problem was this:
  checking the takout on google there was now one file more... (i.e. there is a no. **22** shown in the meantime)
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/2521028/51d1f62b-258c-48cc-8db1-b1b9bd99fac7)

when i got the message from google, "export done" there where **21** export-files (yes the whole is a large export. i have about 528 albums | 67402 pictures)

after downloading 21 and 22 again, adding the extract to AllTakeouts folder, the command succeeded:
`D:\google-photos-takeout>gpth-windoza.exe -i AllTakeouts -o "photos-for-import"  --albums duplicate-copy --skip-extras --guess-from-name --copy

>Guessing dates from files : ███████████████████████████████████████. 4915/4972
>Finding albums (this may take some time, dont worry :) ...
>Coping photos to output folder : ████████████████████████████████████████ 4972/4972
>========================================
>DONE! FREEEEEDOOOOM!!!
>Skipped 1570 extras
>Couldn't find date for 53 photos/videos :/

>Last thing - I've spent *a ton* of time on this script -
>if I saved your time and you want to say thanks, you can send me a tip:
>https://www.paypal.me/TheLastGimbus
>https://ko-fi.com/thelastgimbus
>Thank you ❤
>========================================

**Comment by TheLastGimbus** [comment]
You still have it wrong. You move all individiual folders named "Takeout" (with the upper T) *from* folders like "takeout-202003...", and merge them so that you and up with only a single `Takeout` folder. Your screenshots shows that you still have them inside those "takeout-2020..." folders.

I don't know if what you did now will work 100%, but would recommend to repeat it again the correct way :+1:

**Comment by hugoduraes** [comment]
@TheLastGimbus I think I might be having the same issue. The I unzip the files I get a `Takeout` folder from which one, which I rename to something like `takeout-2024050910515012-001` and move to inside a global takeout folder. I end up getting this file structure:

```
takeout
   takeout-2024050910515012-001
   takeout-2024050910515012-002
   takeout-2024050910515012-003
```

Is this how it's supposed to be? Or should the `takeout` folder have only the contents of all the `takeout-2024050910515012-*` folders?
If it's the latter, on a Mac, how do I merge folders with the same name into one folder?

Thanks

**Comment by TheLastGimbus** [comment]
> rename to something like

no renaming, no no no

> Is this how it's supposed to be?

Nope, still not

I don't know how to put it in other words, i already written and drawn everything... just copy and paste each folder named "Takeout" into single location to merge it 

> how do I merge folders with the same name into one folder?

Your system should ask you to do it when you paste same folder into same place

**Comment by ong-andrew** [comment]
> ![2024-05-10_dartFolderClassify](https://private-user-images.githubusercontent.com/2521028/329663951-7c313ce1-5abb-432e-8003-4104879e5496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzQ5MDYsIm5iZiI6MTcyNTIzNDYwNiwicGF0aCI6Ii8yNTIxMDI4LzMyOTY2Mzk1MS03YzMxM2NlMS01YWJiLTQzMmUtODAwMy00MTA0ODc5ZTU0OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMjM1MDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2MwYzE4YTQ0MDk4YTc1NTFmN2NmYTU4ZmI5OWEyODRlOWJkOTM5YmVjZDUxYWVlNmRhMzFmNWVkNmY0MWM3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FvCIckHrFfiYdckNX19Zy000YaX4rGUCe__N1eGlt-Q)
> 
> stupid question: does this really match to one of my year folders?
> 
> would following not deliver a successful match ?
> 
>     * year-folder: takeout-**20240509**T051501Z-001
> 
>     * `(19|20)\d{2} <== year any from 19[00] up to 20[99]`
> 
>     * `(0[1-9]|1[1,2]) <== month [00 to 12]`
> 
>     * `(0[1-9]|[12][0-9]|3[01])  <== day [01 to 31]`

Thanks for pointing this out. 

The script expects to find a folder with "Photos from YYYY".

Sometimes, the exports from Google Takeout does not name the folders as such. 

Renaming the folders does the trick. (e.g. original "~/Downloads/Takeout/Google Photos/Some_Album" to "~/Downloads/Takeout/Google Photos/Photos from YYYY")

**Comment by mthines** [comment]
I got this error as well, and figure out it downloaded files from Takedown were translated into danish, resulting in the `isYearFolder` function now matching - returning the error.
I renamed all the year folders from danish "Billeder fra 2014" etc, to "Photos from 2014", and then it worked.

Ideally the logic should be sensitive to language, but I get that adds potential for other issues by matching not year folders, so perhaps just adding a note in the readme that the years folder must match the expected syntax?

Thanks for making this script anyway :)

**Comment by diestor** [comment]
> I got this error as well, and figure out it downloaded files from Takedown were translated into danish, resulting in the `isYearFolder` function now matching - returning the error. I renamed all the year folders from danish "Billeder fra 2014" etc, to "Photos from 2014", and then it worked.
> 
> Ideally the logic should be sensitive to language, but I get that adds potential for other issues by matching not year folders, so perhaps just adding a note in the readme that the years folder must match the expected syntax?
> 
> Thanks for making this script anyway :)

Yeah, what this guy said, the name of the folders must be "GOOGLE PHOTOS" and inside them "PHOTOS FROM XXXX" that's it.
