### ISSUE TITLE
Filesystem date fix feature

### ISSUE THREAD

**Issue by varnav** [TheLastGimbus/GooglePhotosTakeoutHelper#31]
Hi!

I noticed that many apps will sort by filesystem date which is often wrong. I made a tool to modify filesystem date according to EXIF date. You may want to port some code from it for your tool.
Please take a look:
https://github.com/varnav/ExifDate2FS/

**Comment by TheLastGimbus** [comment]
Oh, I've seen you on Reddit!

I looked at your code, and we already do everything that you do, but thanks for proposition!

But while maintaining this, many people showed up with some *really weird* exif formats, so the [script does a lot of `.replace()` to handle this...](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/686bbf9047df70838e8cc661cff9aaa789bccec0/google_photos_takeout_helper/__main__.py#L310)

Also, in [`issame()`](https://github.com/varnav/ExifDate2FS/blob/19364bae2bec85cbf7309b3c9cc6b25044bde227/ExifDate2FS.py#L21), you can save some time by checking the file size first - take a look what was done in #11
