### ISSUE TITLE
Is this project needed for re-uploading to Google Photos?

### ISSUE THREAD

**Issue by ShlomoCode** [TheLastGimbus/GooglePhotosTakeoutHelper#311]
I have a corporate account with a lot of content on Google Photos, I downloaded takeout to simply re-upload it to my personal account's Google Photos.
From your experience, in such a case, is this great tool necessary? Or will Google know how to get along with its files without help? 😀
Thanks!

**Comment by palijn** [comment]
I don't see how it could do that. In my experience Google Takeout garbles the included EXIF data in the picture file, and spits the original values out in an accompanying .json file. I am not aware of any way to import photos in Google *with the .json* file.

**Comment by ShlomoCode** [comment]
> In my experience Google Takeout garbles the included EXIF data in the picture file

Interesting, I opened photo files from takeout in Windows Photos, and I see the location where it was taken, the details of the device that took the photo, date, etc.

**Comment by palijn** [comment]
The whole point of this program is that Google Takeout has a tendency to modify the included date to something different from the original (which I called "garble", not in the sense that a program can't read it but that it has no value for the picture owner).
If you don't hit that issue, then 1) you're lucky 2) you don't need gpth.
As a quick check, if there are json files near your originals in the Takeout, have a look at the data in there and compare to the data in the photo. If they're the same, great for you ! :)

**Comment by TheLastGimbus** [comment]
> In my experience Google Takeout garbles the included EXIF data

Hey, we talked about it many many times, and it looks like it doesn't - #191 and few other discussions found no solid pattern that Google does indeed strip exif. I can say for 100% that it didn't for me...

> Google Takeout has a tendency to modify the included date to something different from the original

Also very much not true. Only thing the takeout process does, is that when you download files, their "fileModifiedDate" properties are all set to today - which happens 99% of the time when you download something from internet

only thing that gpth does is it organises all of them out of their weird folders and puts then into single big one, and sets all "fileModifyDate" values correct. But, it does so, often, by reading the photo's exif metadata, which is 90% of times present and correct


Answering your question @ShlomoCode, I'm not sure if google will nicely support uploading their own takeout back to themselves (probably not), so I think running gpth before that is pretty good idea :+1:
