### ISSUE TITLE
All Dates are Today

### ISSUE THREAD

**Issue by huangrant** [TheLastGimbus/GooglePhotosTakeoutHelper#312]
Hello, 

First off, thanks for this tool. It's amazing! 

I'm running into an interesting issue where the dates in the photos are the date/time when it's run? It's very weird because the first time I used it and worked out great (all the timestamps were perfect and in order) & I thought I was done so I closed gpth-macos, but then after I closed it all the dates became today. I can't remember if I called it a day and closed the terminal before I pressed enter to exit gpth in terminal. 

So since then I have tried redownloading my takeout files 3 times from Google, and also downloading a clean version of gpth, but now every time it runs the photo date/time is when it runs... 

Not sure what could be wrong, but so interesting.. 

Again, thanks.

**Comment by huangrant** [comment]
Oh, looks like the metadata is placed as the modified date? Will consider this fixed.

**Comment by TheLastGimbus** [comment]
Yes, gpth modifies only "file modified date"

When **you** said "photo dates", you ment:
- file modifed
- file created
- or exif metadata date?
