### ISSUE TITLE
PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub

### ISSUE THREAD

**Issue by minhchung** [TheLastGimbus/GooglePhotosTakeoutHelper#316]
![Screenshot 2024-06-06 192720](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/4857216/0bc72eab-6dd6-43df-8f71-5c0132022710)

**Comment by TheLastGimbus** [comment]
Yeaah, that's a thing. Thanks for reporting but i don't plan much on fixing this :shrug:
