### ISSUE TITLE
Request to prepend files with original dates

### ISSUE THREAD

**Issue by DanielRunningen** [TheLastGimbus/GooglePhotosTakeoutHelper#320]
Hello!

I know there is an option to guess a file's date from it's name, but I'm almost wondering if the opposite is possible? This would be helpful in the cases where files originated from multiple devices, giving some with dates and some without, and the end user would like to be able to scroll through the "All" folder by chronological order. I know this wouldn't fix the files where a date could not be predicted/parsed, but it would be a huge improvement that mitigates the need for year/month/(day) folders in our use case. It also would make this information system agnostic, and transferable for the less tech-savvy folks who intend to move files around after this process is complete.

Ideally if an item already has a date in the name (like `20240618_123456.jpg`), that date could be parsed nicely and re-appended (e.g. `2024-06-18_123456.jpg`) to make it more human-readable. If it doesn't already have the date (as in `IMG_XYZ.jpg`), but it can be retrieved by the metadata, then a prepend would be ideal (resulting in `2024-06-18_IMG_XYZ.jpg`).

Thanks for the awesome tool though! It's already been really helpful!

**Comment by TheLastGimbus** [comment]
yeahh, the naming stuff is cool, but i think it's a bit bit out of scope here, and actaully so simple to write in python that you can do it yourself in literally 5 lines or so :+1:
