### ISSUE TITLE
use localFolderName

### ISSUE THREAD

**Issue by Konrni** [TheLastGimbus/GooglePhotosTakeoutHelper#321]
Is it possible to use "localFolderName" from the json file? Or is there interest in it?

`"googlePhotosOrigin": {
    "mobileUpload": {
      "deviceFolder": {
        "localFolderName": "WhatsApp Images"
      },
      "deviceType": "ANDROID_PHONE"
    }
  },`
This might make it easier for locally sorted photos, maybe even nested with before/after "divide-to-dates".

I don't know if this is even their on ios or non mobil uploads tho.

**Comment by TheLastGimbus** [comment]
Describe what you mean by that further?

**Comment by TheLastGimbus** [comment]
Sorry but this seems niche and rare enough that i don't plan on adding this to gpth

reason is that i strongly want to keep gpth as simple as posible, because it already is crazy complicated compared to what it does :100:
