### ISSUE TITLE
Files with Icon but without picture

### ISSUE THREAD

**Issue by JTR7** [TheLastGimbus/GooglePhotosTakeoutHelper#323]
Hello,

First of all thank you so much for this app which resolves a lot of issues and simplifies this exercise. Really appreciate! 

I've executed step by step the process and all pictures and videos are created acccordingly. However, there are a few pictures that appear with one icon but there is no picture. Can you comment what does it mean? Meaning, i cannot open the picture. 

Will past a picture here asap. 

Note: I haven't been through the previous comments/issues yet.

Thank you in advance
Tiago Ribeiro

**Comment by TheLastGimbus** [comment]
this must be an issue from gphotos or something - gpth doesn't actually modify files at all :shrug:
