### ISSUE TITLE
FileSystemException: readInto failed

### ISSUE THREAD

**Issue by ianhuangg** [TheLastGimbus/GooglePhotosTakeoutHelper#328]
I am facing this error on version 3.4.3, was wondering if anyone knew what could be wrong? This error occurred after the "finding duplicates" stage, and all settings were default. I merged multiple takeout folders into one folder and don't really know how to proceed, any help would be appreciated! Thanks in advance!

`Unhandled exception: FileSystemException: readInto failed, path = '/Volumes/MacintoshHD/Users/ianhuang/Documents/Google Photos Backup/Takeout/Google Photos/Photos from 2021/C7C74DA9-B783-4CE3-9192-33E13B65207B.png' (OS Error: Operation canceled, errno = 89)`
`#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:834)`
`#1      _File.readAsBytesSync (dart:io/file_impl.dart:593)`
`#2      Media.hash (package:gpth/media.dart:54)`
`#3      Group.groupIdentical.<anonymous closure> (package:gpth/grouping.dart:30)`
`#4      IterableExtension.groupListsBy (package:collection/src/iterable_extensions.dart:410)`
`#5      Group.groupIdentical (package:gpth/grouping.dart:30)`
`#6      removeDuplicates.<anonymous closure> (package:gpth/grouping.dart:54)`
`#7      MappedIterator.moveNext (dart:_internal/iterable.dart:393)`
`#8      IterableIterableExtension.flattened (package:collection/src/iterable_extensions.dart:880)`
`#9      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554)`
`#10     removeDuplicates (package:gpth/grouping.dart:57)`
`#11     main (file:///Users/runner/work/GooglePhotosTakeoutHelper/GooglePhotosTakeoutHelper/bin/gpth.dart:294)`
`<asynchronous suspension>`

**Comment by TheLastGimbus** [comment]
this is because #251
