### ISSUE TITLE
Albums with diacritics in name fail

### ISSUE THREAD

**Issue by mjurisic** [TheLastGimbus/GooglePhotosTakeoutHelper#329]
Hi,

I had some albums from one of my Croatia trips with diacritics in place names and their import failed.

Not a big deal but the tool said to report it here :) 

Thanks for the cool tool. 

Example output: 
```
Moving photos to output folder : ███████████████████████████████████..... 36543/41204  Creating shortcut for DSC00164(1).JPG in Sonntagnachmittag in Trakošćan failed :(
PowerShell doesnt work :( - report that to @TheLastGimbus on GitHub:
```

**Comment by TheLastGimbus** [comment]
Yeaaah, powershell doesn't like them... can't do much about it :(

thanks for reporting
