### ISSUE TITLE
Grouping screenshots by aspect ratio

### ISSUE THREAD

**Issue by antimofm** [TheLastGimbus/GooglePhotosTakeoutHelper#33]
I don't know how far outside the scope this is (or wether it is possible at all), but it's something I'm currently in need of after having run Takeout so I might as well put it out there: since most of my Google Photos were uploaded from a smartphone, there's an inane amount of screenshots that I'll want to clear out.

If there was a way for the script to recognise and group together screenshots (by looking at the aspect ratio), it would be awesome!

**Comment by TheLastGimbus** [comment]
I don't see this ending up in here, but you can always make a fork and try to do it youself!

I would suggest not looking at pure aspect ratio, but maybe if it is the excact width and height of your display - you could have many portrait photos with 16:9 ratio...

But after all, this is somehow advance photo porcessing/analizing task - nothing we do here, sorry...

**Comment by antimofm** [comment]
It was worth a try - sorry for going OT!

**Comment by TheLastGimbus** [comment]
Hey, so I think I found a pretty decent solution for you!

I just started trying out Photoprism, and it has this option- Quality filter: "Non-photographic and low-quality images require a review before they appear in search results."

That will just filter out all memes and screenshots!
