### ISSUE TITLE
All photos in albums or archive -- issue?

### ISSUE THREAD

**Issue by pjfitzgerald** [TheLastGimbus/GooglePhotosTakeoutHelper#337]
Hi there,

Wondering if I've encountered an edge case, or whether my takeout did indeed get messed up somehow. I got the below error when running gpth on my synology:

```
$ ./gpth-linux --input /input-dir/ --output /output-dir/ --albums "json"
Okay, running... searching for everything in input folder...
...oh :(
...
I couldn't find any D: reasons for this may be:
  - your Takeout doesn't have any "year folders" -
    visit https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper
    again and request new, correct Takeout
After fixing this, go ahead and try again :)
```

My google photos are organised in such a way that there are no photos in the 'main' photos interface, they're all either in albums or in the archive. When using takeout, I selected all 'photos from xxxx' options, as well as the archive. 

Does gpth account for this setup that I have? Maybe it requires me to unarchive all my photos before using takeout?

Thank you!

edit: additional note: i did try running this on a previous takeout where I had selected all album data (including archive), and noticed the gpth output had considerably less photos than I expected. Maybe this is due to the archive not being included?

**Comment by TheLastGimbus** [comment]
> 'main' photos interface, they're all either in albums or in the archive

should be impossible - if you have any photos in album, they automatically show up in a photo roll

...is the command you pasted the actual command you type in? because, you know, you have to actually type paths to your folders... the `/` at begginging indicates that folder is at root, which i think is impossible for normal user setup...

**Comment by pjfitzgerald** [comment]
Thanks for your response. 

> should be impossible - if you have any photos in album, they automatically show up in a photo roll

You can archive photos and still have them remain in albums.  My workflow is to categorise most photos I take into albums, then archive them (and if they don't fit into one of my albums I'll just archive them without putting into an album)-- so the main photos interface ends up empty. I'm wondering whether gpth doesn't account for this situation?

> ...is the command you pasted the actual command you type in? because, you know, you have to actually type paths to your folders... the `/` at begginging indicates that folder is at root, which i think is impossible for normal user setup...

The directories pasted are relative from where I'm running the executable - so don't think that is the problem.

**Comment by akurpanek** [comment]
I have the same error message and scenario. All of my pictures are sorted in albums like "YYYYMM <Eventname>" or "YYYYMMDD <Month>". After that I move the pictures into the archive.
So I my Photostream is empty and ready to process my next pictures.

The metadata files in my takeout are in the same album folder like the pictures.

**Comment by TheLastGimbus** [comment]
@pjfitzgerald 

> directories pasted are relative from where I'm running the executable - so don't think that is the problem

if you really typed them like `/input-dir/`, it *is* a problem. Ready what i said again.

> You can archive photos and still have them remain in albums

ah... didn't think about it.... well, just put at leas one photo in "year folders" and gpth should still find everything, even in archive :ok_hand:
