### ISSUE TITLE
Step 2 question

### ISSUE THREAD

**Issue by bnlove** [TheLastGimbus/GooglePhotosTakeoutHelper#343]
### Discussed in https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/discussions/342

<div type='discussions-op-text'>

<sup>Originally posted by **bnlove** September  2, 2024</sup>
**2. Unzip them all and merge into one, so that all "Takeout" folders become one**

Within each of these Takeout folders is another folder called "Google Photos". So should I end up with one Takeout folder that contains multiple Google Photos folders? If so, should these be "Google Photos 1", "Google Photos 2", etc?

Thanks.</div>

**Comment by Noidea24** [comment]
you should end up with one takeout folder, inside that should be one google photos folder, inside of that should be all your albums.

**Comment by TheLastGimbus** [comment]
Yes
