### ISSUE TITLE
V3.4.0 is the best choice

### ISSUE THREAD

**Issue by AhYazid** [TheLastGimbus/GooglePhotosTakeoutHelper#344]
I have used several types of versions of the GPTH application starting from the latest one, but there is a problem with the application exiting itself when I choose the answer to question number 3, and I tried the version Previously, but still the same as the Windows 10 64bit operating system, finally by trying version 3.4.0 the file successfully repaired the meta data for images and videos.

**Comment by AhYazid** [comment]
I hope you are not confused in trying several versions of the application.

**Comment by TheLastGimbus** [comment]
If you show screenshots and describe in detail what happened when, i may fix it :shrug:
