### ISSUE TITLE
creation time change issues 

### ISSUE THREAD

**Issue by pablo915** [TheLastGimbus/GooglePhotosTakeoutHelper#346]
Hello, 
i was trying to find over internet for solutions about how to connvert that stupid google takeout files into normal one files. Found your guide. Thank you very much for that project. 
Still i have problem with changing creation date of all photos. I downloaded and extracted  exiftool run cmd pasted command but received error 
Error: File not found - defined
Error: File not found - DateTimeOriginal'
    2 directories scanned
 6395 files failed condition
    0 image files read
    2 files could not be read
I tried to remove -if 'not defined DateTimeOriginal' part but that also does not work. What I am doing wrong ?

**Comment by palijn** [comment]
Hello,

there is a problem in your command line, there must be an incorrect or missing quote character somewhere.
Please show the exact command line as you typed it and I may be able to pinpoint the fix.

**Comment by pablo915** [comment]
Hi. Thanks for that fast response. 
First I did cd C:\Users\sectest\Desktop\lol\ALL_PHOTOS\ to go where exiftool is installed
and then 
exiftool -overwrite_original -r -if 'not defined DateTimeOriginal' -P "-AllDates<FileModifyDate" "C:\Users\sectest\Desktop\lol\ALL_PHOTOS\"
to excecute command. Photos are in All_photos folder. exiftool is in lol folder

**Comment by palijn** [comment]
Hi,
as per the exiftool documentation, under the "-if" section there is this example : 
```
# set EXIF ISO value if possible, unless it is set already
exiftool '-exif:iso<iso' -if 'not $exif:iso' 
```

note : single quotes, not double quotes. A single "not" and no "defined" . And the EXIF tag name must start with a $ sign.

**Comment by pablo915** [comment]
Sorry to ask but I cannot manage to make it work, so how command should work? Where this part $exif:iso' should be inserted ? I am really big noob in this stuff.

**Comment by palijn** [comment]
ok, $exit:iso was just the example in the documentation. I would try this command line : 

`exiftool -overwrite_original -r -if 'not $DateTimeOriginal' -P "-AllDates<FileModifyDate" "C:\Users\sectest\Desktop\lol\ALL_PHOTOS"`

I didn't even try to run the command, so, up to you to see and test.

**Comment by pablo915** [comment]
Same resoult as before. Cant manage to make it work

**Comment by pablo915** [comment]
Error: File not found - $DateTimeOriginal'
    2 directories scanned
 6395 files failed condition
    0 image files read
    1 files could not be read

**Comment by TheLastGimbus** [comment]
Just copy the command from the readme sec 5: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper?tab=readme-ov-file#5-most-of-your-photos-should-have-correct-original-exifs-metadata-but-if-you-want-you-can-insert-them-everywhere-with-exiftool-so-you-wont-lose-their-creation-time

and replace last `" /path/to "` stuff with your paths

**Comment by vvirtues** [comment]
I still get
1 directory scanned
925 files failed condition
0 image files read

**Comment by vvirtues** [comment]
using the exact command from readme

**Comment by vvirtues** [comment]
might be windows specific

**Comment by vvirtues** [comment]
-P (-preserve)
         Preserve the filesystem modification date/time ("FileModifyDate")
         of the original file when writing. Note that some filesystems store
         a creation date (ie. "FileCreateDate" on Windows and Mac systems)
         which is not affected by this option. This creation date is
         preserved on Windows systems where Win32API::File and Win32::API
         are available regardless of this setting. For other systems, the
         -overwrite_original_in_place option may be used if necessary to
         preserve the creation date. The -P option is superseded by any
         value written to the FileModifyDate tag.

**Comment by vvirtues** [comment]
this command works for me on windows (original date now shows up for both created and modified, but the created date is there so doesn't matter ig

```cmd
.\"exiftool" -overwrite_original -r -P "-FileCreateDate<FileModifyDate" "C:\Users\ezi24\Pictures\Android DCIM\ALL_PHOTOS/"
```

**Comment by vvirtues** [comment]
this command works for Windows users
replaces creation date with modified date (same as what its supposed to do)
```cmd
.\exiftool -overwrite_original -r -P "-FileCreateDate<FileModifyDate" "C:\Path\To\ALL_PHOTOS/"
```

**Comment by vvirtues** [comment]
@TheLastGimbus i recommend adding to README for all my Windows fellas
