### ISSUE TITLE
struct.error

### ISSUE THREAD

**Issue by Dessel21** [TheLastGimbus/GooglePhotosTakeoutHelper#35]
I am a total noob, please forgive me. The script runs for a while until I get this error:

>  File "c:\users\xy\appdata\local\programs\python\python39\lib\site-packages\piexif\_load.py", line 108, in get_ifd_dict
>     tag_count = struct.unpack(self.endian_mark + "H",
> struct.error: unpack requires a buffer of 2 bytes

I hope someone can help me, I want to finally get away from Google Photos.

**Comment by TheLastGimbus** [comment]
This looks like some really low-level error with exif... Just cut out manually the photo that is causing the problem - that is, the last that was printed on the screen before the error. Then run again and do this for every error like this
