### ISSUE TITLE
Terminal closed and won't work again

### ISSUE THREAD

**Issue by konashevich** [TheLastGimbus/GooglePhotosTakeoutHelper#351]
I was running a windoza script, but the terminal closed by itself, and I’m not sure why. 
I restarted the process, and in the initial prompts, I chose "Continue" using the same folder (without deleting its contents). However, the terminal closed again just a few moments after starting. I’ve repeated this several times, but it keeps closing.

Could this be an issue with disk space? I still have about 3 TB free (7 TB of Takeout on a 10 TB RAID). I’ve already asked once if it needs a space buffer (https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/347), but I was reassured that it moves files rather than copying them. Based on that, I concluded that I don’t need double the volume of my Takeout folder.

Do you have any suggestions on what to do?

**Comment by ttnb0207** [comment]
I am having the same issue. Hoping to find a resolution.
