### ISSUE TITLE
After a few modifications it works for me.

### ISSUE THREAD

**Issue by songhuadan** [TheLastGimbus/GooglePhotosTakeoutHelper#38]
Line 10: `    from datetime import timedelta as _timedelta # used to calculate negative timestamp, i.e. time before 1970`
Line 291: `dir = dir[12:] + ':01:01' + ' 12:00:00' # adapted to the new takeout folder names, e.g. 'Photos from 2020'`
Line 321: ` # if it is before 1970, timestamp needs to be calculated differently, which is also applicable after 1970.`
`timestamp = (_datetime.strptime(str_datetime, '%Y:%m:%d %H:%M:%S') - _datetime(1970, 1, 1)) / _timedelta(seconds=1)`
Line 377: `timestamp_1 = int(json['photoTakenTime']['timestamp'])`
`datetime_1 = _datetime(1970, 1, 1) + _timedelta(seconds=timestamp_1)`
`return datetime_1.strftime('%Y:%m:%d %H:%M:%S')`
Line 550: `date = _datetime(1970, 1, 1) + _timedelta(seconds=creation_date)`

**Comment by hisam88** [comment]
Is this a fix to the current issue with how Google creates folders now? 

If so, could you please explain how I can modify the code so I can use this? 

I tried replacing the lines in the current code with what you wrote, but some did not add up, so it didn’t make much sense.

**Comment by songhuadan** [comment]
Attached is the modified code. It is better to remove the albums. If not, the unidentified files will go to the folder 2020/12.
[__main__.zip](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/5744467/__main__.zip)

**Comment by hisam88** [comment]
> Attached is the modified code. It is better to remove the albums. If not, the unidentified files will go to the folder 2020/12.
> [**main**.zip](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/5744467/__main__.zip)

Remove the albums before using google takeout?

**Comment by songhuadan** [comment]
After download and unzip the takeout zip file, move albums to separate folder. You can still use the code to sort the albums.

**Comment by hisam88** [comment]
Got it. Thanks @songhuadan, I’ll give it a try.

**Comment by Zulex** [comment]
Any comments on this, will try to take out close to 1tb of data anytime soon

**Comment by songhuadan** [comment]
> Any comments on this, will try to take out close to 1tb of data anytime soon

Suggest to try it with a small collection first, e.g. photos from one year or a collection of 1000 photos and videos. You will learn also what might cause problems. It takes many hours to process large number of files. Good luck.

**Comment by TheLastGimbus** [comment]
`pip install google-photos-takeout-helper==2.0.0rc1`
