### ISSUE TITLE
Windoza standalone .exe?

### ISSUE THREAD

**Issue by RaydenX93** [TheLastGimbus/GooglePhotosTakeoutHelper#43]
Hello,
Is it possible to have a standalone exe?
I don't have Python installed on my windows machine and probably neither does the average windows user.

PS. Looking forward to the new release! Keep it up! 👍

**Comment by TheLastGimbus** [comment]
So I borrowed a Windoza laptop from my family and **oh my god** _how_ can people use this 0_o

I got this exe with [https://pypi.org/project/pyinstaller/](https://pypi.org/project/pyinstaller/) - tell me if it works for you - if so, I'll include it in release files

**Comment by RaydenX93** [comment]
Thank you for the effort and for the quick response!
Unfortunately, there are 2 issues with your exe:
1. Windows Smart Screen alert was triggered. This is not a problem per-se but could be a nuisance for non-technical/paranoid users.
2. I tried to launch the exe without any arguments but this error appeared:
![immagine](https://user-images.githubusercontent.com/26058845/103577180-9b45ac80-4ed4-11eb-8f28-f7e39a8513b6.png)

**Comment by TheLastGimbus** [comment]
> Windows Smart Screen

Can't do anything with that. Actually, it's nice that it warns you before launching some random .exe from internet...

> error

Huh... I honestly have no idea how "py to exe" magic works, but I will take a look at that link, and send you results - looks very promising

**Comment by RaydenX93** [comment]
Cool, I'll gladly help you testing, even though I have the new Google Takeout format so for now I'll just try open your exe xD

**Comment by TheLastGimbus** [comment]
Started `pip install Gooey`...

Takes 30 minutes...

Hmmm, why could it take 30 minutes

![windoza_defender](https://user-images.githubusercontent.com/40139196/103822562-4cc91700-5068-11eb-8088-cb4992b08d2b.png)

NO CLUE

<sub>Lucky it's just a vm...</sub>

**Comment by TheLastGimbus** [comment]
Disabled all possible Windoza Defenders... just couldn't install it...

Can someone else do this? Maybe i'll do it with GitHub actions vm ?

**Comment by TheLastGimbus** [comment]
# DONE :tada:

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/releases/tag/v2.1.0

Sorry that this took so long, but this was a **big challange for me*. I've sat few hours with Windoza 10 and Sever 2012 vm's that I have for my school, with no luck, and then sat for another few hours to make a GitHub Action (luckly it works well and perdictive, just very slow to test) - and DONE

above you have your exe in assets

I will add this in README tommorow. I should be asleep 1.5h ago :flushed: :sleeping:

**Comment by RaydenX93** [comment]
Thank you! I will try it out with my takeout ASAP! ;)
