### ISSUE TITLE
Setting right exif date failed

### ISSUE THREAD

**Issue by troyrock** [TheLastGimbus/GooglePhotosTakeoutHelper#49]
I have a takeout where setting the right exif failed for 17,366 files of 48,342 which is almost 36%.  This seems high to me, does that mean that I don't have something installed correctly?  Thanks.

**Comment by TheLastGimbus** [comment]
What files are those? .png? Some file formats just don't support exif, like png - there may be some hacks around it, but it's hard to find good python library that would do that

Although some formats do have exif while `piexif` library doesn't support them, which is a shame

### But don't worry!
If your photos had exif data already, it wil remain

**Comment by troyrock** [comment]
These were all jpg files.

**Comment by TheLastGimbus** [comment]
Could you send me some samples of those files? It could be an issue for `piexif` people...
