### ISSUE TITLE
Files with paranthesis e.g. (1) have differently named JSON files and titles

### ISSUE THREAD

**Issue by rizz360** [TheLastGimbus/GooglePhotosTakeoutHelper#59]
I have the following files:

- `IMG_4081(1).jpg`
- `IMG_4081.JPG(1).json`

Notice how not only the 'jpg' is uppercase for the json (fixed #46)  but also the (1) is placed in the wrong location. To bring this one step further, this is the content of the json:

``````json
{
  "title": "IMG_4081.JPG",
  "description": "",
  "imageViews": "0",
  "creationTime": {
    "timestamp": "1432899863",
    "formatted": "May 29, 2015, 11:44:23 AM UTC"
  },
  ...
}
``````

The title does not have the (1) at all. A big portion of my library has this issue. Is there something wrong with my export or is this yet another annoyance in takeouts?

To be clear, this happens with files that are not duplicates but probably just happened to have the same name upon upload.

Just look at this fun mess:
![image](https://user-images.githubusercontent.com/1228549/106484579-0ec8e280-64b0-11eb-9598-fb60e2fa6bc4.png)

**Comment by hump** [comment]
Same issue here...

Final statistics:
Files copied to target folder: 6666
Removed duplicates: 0
Files for which we couldn't find json: 949

**Comment by rizz360** [comment]
Since #60 has been merged, this can be closed.

**Comment by TheLastGimbus** [comment]
Hey @hump, I just pushed a release that should fix it - can you `pip install -U ...` and compare how many `json not found`s you have?

**Comment by hump** [comment]
my results with latest 2.2.0 

```
Final statistics:
Files copied to target folder: 6666
Removed duplicates: 2
Files for which we couldn't find json: 896

```
BTW: nice progress bar with ETA :)

**Comment by TheLastGimbus** [comment]
Ookaay, to it did help some :rocket: ! For the rest, I tried looking, and some photos just *literally have no exif at all*, so there isn't much to do :confused:

**Comment by hump** [comment]
most images, which have no json, are edited images...

**Comment by rizz360** [comment]
I also noticed that iOS live photos are all kinds of messed up. The moving part of the live photos is exported as a corrupted `...(1).heic` with the same base name as rhe static image. Changing the extension to `.mov` makes it a playable video.

**Comment by TheLastGimbus** [comment]
I am seconds from filling a lawsuit at Google for not complaining at GDPR properly...
