### ISSUE TITLE
Running script - error

### ISSUE THREAD

**Issue by mandraid** [TheLastGimbus/GooglePhotosTakeoutHelper#6]
I am trying to run the script as follows:
`python3 ./setup.py -i photos -o photos-output
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option -i not recognized`

**Comment by TheLastGimbus** [comment]
This script is now packaged as `pip` package - it's not supposed to be cloned and run - rather do what it says in [README](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/master/README.md):

> 1. pip3 install -U google-photos-takeout-helper
> [...]
> 4. Run google-photos-takeout-helper -i [INPUT TAKEOUT FOLDER] -o [OUTPUT FOLDER]
> Alternatively, if you don't have PATH set right, you can call it python3 -m google_photos_takeout_helper
>
> If you previously used this script in form where you download and run it - don't worry! Downloading it with pip is even simpler, and everything will work as previously :)

If you _really_ want to clone and run, you need to run `google_photos_takeout_helper/__main__.py`
