### ISSUE TITLE
Feature Request to Delete Originals

### ISSUE THREAD

**Issue by jshapp** [TheLastGimbus/GooglePhotosTakeoutHelper#64]
Could there be an option to delete the original file so that after running you are left with the new folder of "corrected files" and the old folder of "error files".

**Comment by TheLastGimbus** [comment]
Yes, I was recently thinking about that. Just a simple `--move` flag that will just replace .copy() with .move() 👌

**Comment by jshapp** [comment]
I'm just getting into coding and probably shouldn't be fiddling with projects, but it's fun because this is a tool I actually need right now. 

I attempted to follow your instructions. I added an argument for --move and defined two additional move_to_target type functions that get triggered by elif conditions. 

I was really excited to run/test what I wrote but I couldn't figure out how to run it 😅 . Since I'm running it as a pip install I guess it's running the last released version instead of mine. I don't know what I'm doing haha. I guess I'll wait for someone else to add this and review how they did it.

**Comment by TheLastGimbus** [comment]
Ohhh, really nice that my code is helping you learn!

You sholdn't need a new `move_to` function - just in `copy_to`, right above the `shutil.copy`, do the `if` check - try that out

To run your own version, just do:
```bash
cd projects/GooglePhotosTakeoutHelper
python google_photos_takeout_helper/__main__.py
```
Simple as that

Btw: if anything - <https://realpython.com/> tutorials are SO GREAT! I actually learned how to migrate this project to pypi from them: <https://realpython.com/pypi-publish-python-package/>

**Comment by Que20** [comment]
Hey, any news on this features ? 😇

**Comment by TheLastGimbus** [comment]
Hii! I am generally alive an remember about this, but I still did not have a moment of vein to implement those, sorry :confused: I can't say when I will have a moment, but maybe in a month or something?

**Comment by TheLastGimbus** [comment]
Hi there!

Another 1-year-old-issue

As of `v3.0.0`, moving files is a default :tada:, with a nice `--copy` flag. If you use `--copy`, all files will be copied instead of moved, and input folder will be *untouched* - useful for testing/running when not sure if will work - otherwise, all detected files (that is, only those from "year folders") will be moved to output folder :+1:
