### ISSUE TITLE
Personal roadmap for Takeout Helper

### ISSUE THREAD

**Issue by conradstorz** [TheLastGimbus/GooglePhotosTakeoutHelper#71]
I have a goal to process 196 separate takeout zipfiles. Each file is 2GB and contains only photos/videos.
The roadmap that I have envisioned is to point TakeoutHelper at the base directory containing the takeout zips and then the script would locate all the takeout zips, unzip each one, process the files inside and give me progress reports as it runs.

I'm posting this here to solicit help and ideas so please add your thoughts.

**Comment by TheLastGimbus** [comment]
>  locate all the takeout zips, unzip each one, process the files inside and give me progress reports as it runs.

I think bash would be much more suitable for this:
```bash
for i in *.zip ; do
  unzip $i -d Takeout
  google-photos-takeout-helper -i Takeout/ -o output/
  rm -r Takeout
  alert "Just finished $i"
done
```

**Comment by conradstorz** [comment]
Last night while experimenting with one of my takeout zips and using a
python script to extract the files I discovered a problem. The problem is
with the zip file. Google has used some path names inside the zip file that
are illegal in the windows environment. When I try to unzip these files the
zip process crashes due to the illegal path name. I was able to use my
python script to do a binary read of that file with the bad path and then
write it out to a safe path successfully. these are the kind of problems I
foresee running into when I'm processing 196 different zip files.

I verified that this problem is not because I'm using a python script but
happens even if I ask windows file manager to extract the files I get the
same error and it will not extract any files after it finds one with a bad
path.

**Comment by CephalopodaKingdom** [comment]
This will be my problem in some time too, got 50GB to go through, and I downloaded the first 10 GB for testing out this code. But Seem to have a major struggle figuring out PyCharm / Python. But just asking for future reference, since I believe I will find the solution to my constant failures (errors). What script did you end up using to automatically unzip all your google takeout into one map/file?
