### ISSUE TITLE
Process kills itself without error message.

### ISSUE THREAD

**Issue by evanheckert** [TheLastGimbus/GooglePhotosTakeoutHelper#79]
First off, huge thanks for this script! Hoping I can get it working for my fairly massive dataset. Last few lines of output:

```
There was literally no option to set date on /*snip*/IMG_0077.MOV
There was literally no option to set date on /*snip*/IMG_0864.MOV
There was literally no option to set date on /*snip*/IMG_4031.MOV
There was literally no option to set date on /*snip*/3DCC2641-963F-411E-A2A4-2A0D53D8527A-7119-00000.png
There was literally no option to set date on /*snip*/IMG_0027(1).MOV
There was literally no option to set date on /*snip*/IMG_0238.MOV
  2%|█▌                          | 1556/77872 [04:17<50:10, 25.35files/s][1]    19579 killed     google-photos-takeout-helper -i  -o  --divide-to-dates
➜  Takeout
```

Interestingly, the destination folder is still empty despite the script having processed 1556 items.

Any suggestions on how to troubleshoot?

Thanks!

**Comment by TheLastGimbus** [comment]
> `[1]    19579 killed`

This looks like you killed it with ctrl+z, or your OS killed it :thinking: What OS do you use?

**Comment by evanheckert** [comment]
It does look that way, but not due to any intervention on my part. The actual process is on my home server - Ubuntu Server 20.04 on a i3-10100 with 32gb ram, via an SSH session from my i9 16" Macbook Pro running BigSur 11.2.2. Terminal is iTerm2 3.4.4.

The four-hour process of unzipping 39 zip files at 53GB each completed just find in the same ssh session. I'm connected via gigabit ethernet, so not losing connection. I'm not sure what could be killing it?

**Comment by TheLastGimbus** [comment]
Oh okay, so we are running **big** here

I was actually interested how many "super tech-savy self-hosting 32gb ram server" people are running my script for their 60gb backups... you can tell me some thoughts on how well it does if you have some :+1:

> I'm connected via gigabit ethernet, so not losing connection

Oh, so you ssh into it, and just run it? You can try to do this in separate `screen` session or something

> 53GB

Those are the numbers that I didn't get to test, and my computer would shat itself if I tried :flushed: - can you look at `htop` and see how much it's consuming - maybe it literally eats out whole ram (honestly, I don't really know what it's capable of :fire:)

**Comment by evanheckert** [comment]
Well, the server is actually running Proxmox, and the process is running on a privileged container running Ubuntu Server. I'll shut down the VMs to isolate resource usage and try again.

Ah, that was a good call! Watching it on netstat, and sure enough, it hits a massive video file, fills up the allocated 4GB of ram, then fills up the 4GB swap, and kills itself. I forgot that I'd allocated such a small amount of RAM to the NAS container. It looks like the folder it was working on has a 9 gig mov file. I'll change it to allow up to 12gb and try again.

I do find it odd that nothing was written to the destination folder, still?

**Comment by evanheckert** [comment]
And sure enough, it got past the previous sticking point. So it may be valuable to add to docs to make sure your system has RAM + SWAP larger than the largest file it'll need to deal with.

Another thing I'm noticing is that it's not exceeding 16% CPU (using one of six cores, presumably). I have no idea whether there are libraries that would make it straightforward to use more cores? 

Granted, it's still going quick enough that it's estimating around 2hrs for a little over 2 terrabytes, so probably not worth much effort to speed it up since it's a one-off need.

I'll let you know if I hit any other snags - thanks for the dialogue, and thanks again for such a handy script!

**Comment by TheLastGimbus** [comment]
> RAM + SWAP larger than the largest file it'll need to deal with

Whoa whoa... that's probably because we are calculating full sha1 hash for every file to check for duplicates. I could add some flag to skip it if you/someone wants :+1:

> around 2hrs for a little over 2 terrabytes

In my sense, it is possible to optimize this whole thing to run in something like 1.2x time of what it would take to just copy them (by the way, you can pase here the results of how much each part took) - but that would require pretty much re-writing the whole thing
