### ISSUE TITLE
Keep manually created folder structure not just dates

### ISSUE THREAD

**Issue by sp4ke** [TheLastGimbus/GooglePhotosTakeoutHelper#86]
Hi, 

I have a lot of manually created folders. Google exports the photos duplicated once on the manually created folders on Google Photos app and an other one on the "Photos from <year>" folder. 

I would like to be able to use this script and keep the original folder structure, not just the date based folders as currently implemented. Any tips on where should I look or start to modify the script accordingly ?

**Comment by TheLastGimbus** [comment]
Hmm... maybe `--albums json` would help you? It will output .json file with data about which photo belongs to which album. This is kinda experimental/not well tested tho... but should work :+1:

**Comment by TheLastGimbus** [comment]
Besides, this script fixes files *inside* input directory, and *then* copies them (I know, kinda messy :grimacing:) - so you can just take the ones from `INPUT_DIR`, and they should be fixed - just remove all `.json`s and you're done!

**Comment by sp4ke** [comment]
Thanks a lot for the details your last solutions seems the best :)

**Comment by brianreese** [comment]
Thanks, I was also hoping to preserve the folder structure created by my google photos albums, so using the input dir files works out well for me too
