### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by joey2031** [TheLastGimbus/GooglePhotosTakeoutHelper#94]
I just used this, I love it! However, I have some ideas that might make this better:
- I think the UX could be better if the months were labeled as Jan, Feb etc..
- [x] Also, I tried to use the exe file but windows was not letting me run it so I ended up using pip. 
- [ ] It would be cool if you rename the file as the date of the photo since Windows organizes the file names alpha order, this way when the user is viewing everything they can see all birthday photos together, all grad photos togther etc... 
Overall, great program, saved my life :) 

(edits from @TheLastGimbus - I added the "[ ]" to mark progress

**Comment by TheLastGimbus** [comment]
*(Will this work (display nice in issue progress) if i put it like this?)*

- [ ] See if there's something wrong with .exe or is it just windoza
- [ ] option to rename photos to dates

If anyone has a problem with running .exe, please post it here, as descriptive as possible :ok_hand:

**Comment by TheLastGimbus** [comment]
Hi there! Working on `v3` now, and those seem interesting. To summarize:
- [ ] sign windoza .exe to make defender happy
- [ ] rename files to their dates to be good even when something changes their modify date

**Comment by TheLastGimbus** [comment]
closing with f3438eeb - exifs should be good enough instead of renaming photos :+1:
