### ISSUE TITLE
Why are all images put into one folder?

### ISSUE THREAD

**Issue by eaigner** [TheLastGimbus/GooglePhotosTakeoutHelper#98]
I don't know what the reasoning is behind destroying all folder/album names and putting everything in one big folder.

**Comment by TheLastGimbus** [comment]
Umm... it's the main reason of this script existence, and is written in readme: takeout export gives you tens (used to be hundreds, now it's just per-year) folders + `.json` files. It's impossible to copy them to your phone/import into other photo-managment app in that form...

Reason why it doesn't keep album names is... well, complicated. We ( https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/10#issuecomment-738517216 #36 ) couldn't find good solution to store them, nor even a way to figure out which photos are from which album :confounded: :confounded:
