### ISSUE TITLE
Output folder empty

### ISSUE THREAD

**Issue by titus483** [TheLastGimbus/GooglePhotosTakeoutHelper#99]
Hi, I installed the GPTH via pip on a Windows 10 system.
I used it with 2 completely different folders (as input/output). This worked perfectly.
Then I used "C:\Users\xxx\Pictures\JFN" as input and "C:\Users\xxx\JF" as ouput. I.e. the output folder name was in part identical with the input folder name - but just shorter.
And to my surprise: no photos were copied to the folder name (the log did not mention any problem). I tried the same with the--divide-to-dates option, but with the same result. 
This could be a bug (not a very serious one I admit), but if somebody else could verify this I would consider it as bug.

Titus

**Comment by TheLastGimbus** [comment]
There should be some `file_{time}.log` file with all logs - could you upload/paste it here?

**Comment by titus483** [comment]
Well, here they are. The first 2 are the ones where the folder remained empty. The last one from after I changed the folder names and it worked.
BUT: When I tried to reproduce the problem today, I failed. So I'm not sure what and why it happened. 
[file_2021-09-19_21-42-04_791443.log](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/7219395/file_2021-09-19_21-42-04_791443.log
[file_2021-09-19_22-07-03_006948.log](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/7219396/file_2021-09-19_22-07-03_006948.log)
[file_2021-09-19_22-24-10_484065.log](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/files/7219397/file_2021-09-19_22-24-10_484065.log)
)
